from __future__ import annotations

MACRO_VIEW_PROJECTION_VERSION = "macro_regime_v4"
MACRO_MODULE_VIEW_VERSION = "macro_module_view_v3"
MACRO_VIEW_HISTORY_LOOKBACK_DAYS = 1095
MACRO_VIEW_HISTORY_LIMIT_PER_SERIES = 800
MACRO_MIN_CHART_POINTS = 2
MACRO_REQUIRED_DELTA_POINTS = {"5d": 6, "20d": 21, "60d": 61}
MACRO_REQUIRED_STAT_POINTS = 126

MACRO_PROVIDER_SERIES_TO_CONCEPT = {
    "fred:WALCL": "liquidity:fed_assets",
    "fred:WRBWFRBL": "liquidity:reserve_balances",
    "fred:RRPONTSYD": "liquidity:on_rrp",
    "nyfed:RRP": "liquidity:nyfed_rrp",
    "nyfed:SRF": "liquidity:srf",
    "nyfed:SOFR": "liquidity:sofr",
    "treasury_fiscal:operating_cash_balance": "liquidity:tga",
    "fred:DFF": "fed:dff",
    "fred:DGS1MO": "rates:dgs1mo",
    "fred:DGS3MO": "rates:dgs3mo",
    "fred:DGS6MO": "rates:dgs6mo",
    "fred:DGS1": "rates:dgs1",
    "fred:DGS2": "rates:dgs2",
    "fred:DGS3": "rates:dgs3",
    "fred:DGS5": "rates:dgs5",
    "fred:DGS7": "rates:dgs7",
    "fred:DGS10": "rates:dgs10",
    "fred:DGS20": "rates:dgs20",
    "fred:DGS30": "rates:dgs30",
    "fred:T10Y2Y": "rates:10y2y",
    "fred:T10Y3M": "rates:10y3m",
    "fred:DFII5": "rates:real_5y",
    "fred:DFII10": "rates:real_10y",
    "fred:DFII30": "rates:real_30y",
    "fred:T5YIE": "inflation:5y_breakeven",
    "fred:T10YIE": "inflation:10y_breakeven",
    "fred:T5YIFR": "inflation:5y5y_forward",
    "fred:MICH": "inflation:mich_1y_expectation",
    "fred:DFEDTARU": "fed:target_upper",
    "fred:DFEDTARL": "fed:target_lower",
    "fred:FEDFUNDS": "fed:fedfunds",
    "fred:EFFR": "fed:effr",
    "fred:IORB": "fed:iorb",
    "fred:SOFR30DAYAVG": "fed:sofr_30d",
    "fred:GDP": "economy:gdp_nominal",
    "fred:GDPC1": "economy:gdp_real",
    "fred:GDPDEF": "inflation:gdp_deflator",
    "fred:UNRATE": "labor:unemployment",
    "fred:PAYEMS": "labor:payrolls",
    "fred:CIVPART": "labor:participation",
    "fred:ICSA": "labor:initial_claims",
    "fred:JTSJOL": "labor:job_openings",
    "fred:CPIAUCSL": "inflation:cpi",
    "fred:CPILFESL": "inflation:core_cpi",
    "fred:PPIACO": "inflation:ppi",
    "fred:PCEPI": "inflation:pce",
    "fred:PCEPILFE": "inflation:core_pce",
    "fred:PCE": "consumer:pce_nominal",
    "fred:PCEC96": "consumer:pce_real",
    "fred:RSAFS": "consumer:retail_sales",
    "fred:INDPRO": "economy:industrial_production",
    "fred:HOUST": "economy:housing_starts",
    "fred:UMCSENT": "consumer:umich_sentiment",
    "fred:PSAVERT": "consumer:saving_rate",
    "fred:BAMLC0A0CM": "credit:ig_oas",
    "fred:BAMLC0A1CAAA": "credit:aaa_oas",
    "fred:BAMLC0A2CAA": "credit:aa_oas",
    "fred:BAMLC0A3CA": "credit:a_oas",
    "fred:BAMLC0A4CBBB": "credit:bbb_oas",
    "fred:BAMLH0A0HYM2": "credit:hy_oas",
    "fred:BAMLH0A1HYBB": "credit:hy_bb_oas",
    "fred:BAMLH0A2HYB": "credit:hy_b_oas",
    "fred:BAMLH0A3HYC": "credit:hy_ccc_oas",
    "fred:BAMLC0A0CMEY": "credit:ig_yield",
    "fred:BAMLH0A0HYM2EY": "credit:hy_yield",
    "fred:STLFSI4": "credit:stl_stress",
    "fred:NFCI": "credit:nfci",
    "fred:ANFCI": "credit:anfci",
    "fred:VIXCLS": "vol:vix",
    "fred:VXVCLS": "vol:vix3m",
    "fred:VXNCLS": "vol:vxn",
    "fred:RVXCLS": "vol:rvx",
    "fred:GVZCLS": "vol:gvz",
    "fred:OVXCLS": "vol:ovx",
    "fred:EVZCLS": "vol:evz",
    "fred:SP500": "asset:spx",
    "fred:NASDAQCOM": "asset:nasdaq",
    "fred:DCOILWTICO": "commodity:wti",
    "fred:DCOILBRENTEU": "commodity:brent",
    "fred:DHHNGSP": "commodity:natgas",
    "fred:DTWEXBGS": "fx:broad_dollar",
    "fred:DEXUSEU": "fx:fred_eurusd",
    "fred:DEXJPUS": "fx:fred_usdjpy",
    "fred:DEXCHUS": "fx:fred_usdcny",
    "fred:DEXUSUK": "fx:fred_gbpusd",
    "yahoo:SPY": "asset:spy",
    "yahoo:QQQ": "asset:qqq",
    "yahoo:DIA": "asset:dia",
    "yahoo:IWM": "asset:iwm",
    "yahoo:EFA": "asset:efa",
    "yahoo:EEM": "asset:eem",
    "yahoo:SHY": "asset:shy",
    "yahoo:IEF": "asset:ief",
    "yahoo:TIP": "asset:tip",
    "yahoo:BND": "asset:bnd",
    "yahoo:TLT": "asset:tlt",
    "yahoo:HYG": "asset:hyg",
    "yahoo:JNK": "asset:jnk",
    "yahoo:LQD": "asset:lqd",
    "yahoo:GLD": "asset:gld",
    "yahoo:SLV": "asset:slv",
    "yahoo:USO": "asset:uso",
    "yahoo:VIXY": "asset:vixy",
    "yahoo:GC=F": "commodity:gold_futures",
    "yahoo:CL=F": "commodity:wti_futures",
    "yahoo:UNG": "asset:ung",
    "yahoo:CPER": "asset:cper",
    "yahoo:UUP": "asset:uup",
    "yahoo:FXE": "asset:fxe",
    "yahoo:FXY": "asset:fxy",
    "yahoo:DX-Y.NYB": "fx:dxy",
    "yahoo:EURUSD=X": "fx:eurusd",
    "yahoo:USDJPY=X": "fx:usdjpy",
    "yahoo:BTC-USD": "crypto:btc",
    "yahoo:ETH-USD": "crypto:eth",
    "cftc:financial_futures:sp500_net_noncommercial": "positioning:sp500_net_noncommercial",
}

MACRO_PROVIDER_SERIES_SOURCE_PRIORITY = {series_key: 100 for series_key in MACRO_PROVIDER_SERIES_TO_CONCEPT}

MACRO_CORE_CONCEPTS = tuple(dict.fromkeys(MACRO_PROVIDER_SERIES_TO_CONCEPT.values()))
MACRO_OPTIONAL_HISTORY_CONCEPTS = ("positioning:sp500_net_noncommercial",)
MACRO_HISTORY_REQUIRED_CONCEPTS = tuple(
    concept_key for concept_key in MACRO_CORE_CONCEPTS if concept_key not in MACRO_OPTIONAL_HISTORY_CONCEPTS
)
MACRO_HISTORY_REQUIRED_POINTS_BY_CONCEPT = {
    "consumer:pce_nominal": 24,
    "consumer:pce_real": 24,
    "consumer:retail_sales": 24,
    "consumer:saving_rate": 24,
    "consumer:umich_sentiment": 24,
    "economy:gdp_nominal": 8,
    "economy:gdp_real": 8,
    "economy:housing_starts": 24,
    "economy:industrial_production": 24,
    "inflation:core_pce": 24,
    "fed:fedfunds": 24,
    "inflation:cpi": 24,
    "inflation:core_cpi": 24,
    "inflation:gdp_deflator": 8,
    "inflation:mich_1y_expectation": 24,
    "inflation:pce": 24,
    "inflation:ppi": 24,
    "labor:job_openings": 24,
    "labor:participation": 24,
    "labor:payrolls": 24,
    "labor:unemployment": 24,
    "positioning:sp500_net_noncommercial": 1,
}

MACRO_CONCEPT_METADATA = {
    "asset:gld": {
        "label": "黄金 ETF",
        "short_label": "GLD",
        "description": "黄金避险与实际利率敏感资产",
        "unit_label": "美元",
    },
    "asset:gspc": {
        "label": "标普500 指数",
        "short_label": "S&P 500",
        "description": "Yahoo 标普500 价格代理",
        "unit_label": "点",
    },
    "asset:hyg": {
        "label": "高收益债 ETF",
        "short_label": "HYG",
        "description": "信用风险偏好的可交易确认",
        "unit_label": "美元",
    },
    "asset:ief": {
        "label": "7-10年美债 ETF",
        "short_label": "IEF",
        "description": "中长久期美债可交易代理",
        "unit_label": "美元",
    },
    "asset:ixic": {
        "label": "纳斯达克综合指数",
        "short_label": "Nasdaq",
        "description": "美国科技成长股风险偏好代理",
        "unit_label": "点",
    },
    "asset:iwm": {
        "label": "罗素2000 ETF",
        "short_label": "IWM",
        "description": "美国小盘股风险偏好代理",
        "unit_label": "美元",
    },
    "asset:lqd": {
        "label": "投资级债 ETF",
        "short_label": "LQD",
        "description": "投资级信用与久期组合代理",
        "unit_label": "美元",
    },
    "asset:qqq": {
        "label": "纳指100 ETF",
        "short_label": "QQQ",
        "description": "美国成长股风险偏好代理",
        "unit_label": "美元",
    },
    "asset:spx": {
        "label": "标普500",
        "short_label": "SPX",
        "description": "美国大盘股风险偏好基准",
        "unit_label": "点",
    },
    "asset:spy": {
        "label": "标普500 ETF",
        "short_label": "SPY",
        "description": "美国大盘股可交易风险偏好代理",
        "unit_label": "美元",
    },
    "asset:shy": {
        "label": "1-3年美债 ETF",
        "short_label": "SHY",
        "description": "短久期美债可交易代理",
        "unit_label": "美元",
    },
    "asset:tlt": {
        "label": "长期美债 ETF",
        "short_label": "TLT",
        "description": "长久期利率敏感资产代理",
        "unit_label": "美元",
    },
    "asset:uso": {
        "label": "原油 ETF",
        "short_label": "USO",
        "description": "原油价格冲击的可交易代理",
        "unit_label": "美元",
    },
    "asset:vixy": {
        "label": "VIX 短期期货 ETF",
        "short_label": "VIXY",
        "description": "VIX 期货敞口的可交易代理",
        "unit_label": "美元",
    },
    "commodity:gold_futures": {
        "label": "黄金期货",
        "short_label": "Gold",
        "description": "COMEX 黄金期货价格代理",
        "unit_label": "美元",
    },
    "commodity:wti_futures": {
        "label": "WTI 期货",
        "short_label": "CL",
        "description": "NYMEX WTI 原油期货价格代理",
        "unit_label": "美元",
    },
    "commodity:wti": {
        "label": "WTI 原油",
        "short_label": "WTI",
        "description": "美元计价原油现货基准",
        "unit_label": "美元/桶",
    },
    "credit:hy_oas": {
        "label": "高收益债 OAS",
        "short_label": "HY OAS",
        "description": "美国高收益债信用利差压力",
        "unit_label": "%",
    },
    "credit:bbb_oas": {
        "label": "BBB 信用利差",
        "short_label": "BBB OAS",
        "description": "美国 BBB 级公司债 OAS 压力",
        "unit_label": "%",
    },
    "credit:hy_bb_oas": {
        "label": "BB 高收益利差",
        "short_label": "BB OAS",
        "description": "高收益债 BB 档 OAS 压力",
        "unit_label": "%",
    },
    "credit:hy_b_oas": {
        "label": "B 高收益利差",
        "short_label": "B OAS",
        "description": "高收益债 B 档 OAS 压力",
        "unit_label": "%",
    },
    "credit:hy_ccc_oas": {
        "label": "CCC 高收益利差",
        "short_label": "CCC OAS",
        "description": "高收益债 CCC 及以下 OAS 压力",
        "unit_label": "%",
    },
    "credit:hy_yield": {
        "label": "高收益债到期收益率",
        "short_label": "HY YTW",
        "description": "美国高收益债综合融资成本代理",
        "unit_label": "%",
    },
    "credit:ig_oas": {
        "label": "投资级债 OAS",
        "short_label": "IG OAS",
        "description": "美国投资级债信用利差压力",
        "unit_label": "%",
    },
    "credit:ig_yield": {
        "label": "投资级债到期收益率",
        "short_label": "IG YTW",
        "description": "美国投资级公司债综合融资成本代理",
        "unit_label": "%",
    },
    "consumer:retail_sales": {
        "label": "零售销售",
        "short_label": "Retail",
        "description": "美国零售销售名义总额",
        "unit_label": "百万美元",
    },
    "consumer:umich_sentiment": {
        "label": "密歇根消费者信心",
        "short_label": "UMich",
        "description": "密歇根大学消费者信心指数",
        "unit_label": "点",
    },
    "crypto:btc": {
        "label": "比特币",
        "short_label": "BTC",
        "description": "加密资产宏观风险偏好代理",
        "unit_label": "美元",
    },
    "crypto:eth": {
        "label": "以太坊",
        "short_label": "ETH",
        "description": "智能合约资产宏观风险偏好代理",
        "unit_label": "美元",
    },
    "fed:effr": {
        "label": "有效联邦基金利率",
        "short_label": "EFFR",
        "description": "隔夜政策利率成交基准",
        "unit_label": "%",
    },
    "fed:fedfunds": {
        "label": "联邦基金有效月均",
        "short_label": "Fed Funds",
        "description": "联邦基金有效利率月度均值",
        "unit_label": "%",
    },
    "fed:iorb": {
        "label": "准备金余额利率",
        "short_label": "IORB",
        "description": "美联储管理利率走廊上沿锚",
        "unit_label": "%",
    },
    "fed:sofr_30d": {
        "label": "SOFR 30日均值",
        "short_label": "SOFR 30D",
        "description": "SOFR 30日平均水平",
        "unit_label": "%",
    },
    "fed:target_lower": {
        "label": "联邦基金目标下限",
        "short_label": "FF 下限",
        "description": "FOMC 目标区间下限",
        "unit_label": "%",
    },
    "fed:target_upper": {
        "label": "联邦基金目标上限",
        "short_label": "FF 上限",
        "description": "FOMC 目标区间上限",
        "unit_label": "%",
    },
    "fx:broad_dollar": {
        "label": "广义美元指数",
        "short_label": "Broad USD",
        "description": "贸易加权美元压力基准",
        "unit_label": "点",
    },
    "fx:dxy": {
        "label": "美元指数",
        "short_label": "DXY",
        "description": "美元兑主要货币强弱代理",
        "unit_label": "点",
    },
    "fx:eurusd": {
        "label": "欧元兑美元",
        "short_label": "EURUSD",
        "description": "欧元兑美元汇率代理",
        "unit_label": "汇率",
    },
    "fx:usdjpy": {
        "label": "美元兑日元",
        "short_label": "USDJPY",
        "description": "美元兑日元汇率代理",
        "unit_label": "汇率",
    },
    "economy:gdp_real": {
        "label": "实际 GDP",
        "short_label": "Real GDP",
        "description": "美国实际国内生产总值",
        "unit_label": "十亿美元",
    },
    "inflation:10y_breakeven": {
        "label": "10年通胀盈亏平衡",
        "short_label": "10Y BEI",
        "description": "市场隐含长期通胀预期",
        "unit_label": "%",
    },
    "inflation:cpi": {
        "label": "CPI",
        "short_label": "CPI",
        "description": "美国居民消费价格指数",
        "unit_label": "指数",
    },
    "inflation:core_cpi": {
        "label": "核心 CPI",
        "short_label": "Core CPI",
        "description": "剔除食品和能源后的 CPI",
        "unit_label": "指数",
    },
    "inflation:5y5y_forward": {
        "label": "5年5年远期通胀",
        "short_label": "5Y5Y",
        "description": "远期通胀预期锚定程度",
        "unit_label": "%",
    },
    "inflation:ppi": {
        "label": "PPI",
        "short_label": "PPI",
        "description": "美国生产者价格指数",
        "unit_label": "指数",
    },
    "labor:initial_claims": {
        "label": "首次申领失业金",
        "short_label": "Claims",
        "description": "美国首次申领失业救济人数",
        "unit_label": "人",
    },
    "labor:payrolls": {
        "label": "非农就业",
        "short_label": "Payrolls",
        "description": "美国非农就业总人数",
        "unit_label": "千人",
    },
    "labor:unemployment": {
        "label": "失业率",
        "short_label": "Unemployment",
        "description": "美国 U-3 失业率",
        "unit_label": "%",
    },
    "liquidity:fed_assets": {
        "label": "美联储总资产",
        "short_label": "Fed 资产",
        "description": "美联储资产负债表规模",
        "unit_label": "百万美元",
    },
    "liquidity:on_rrp": {
        "label": "隔夜逆回购",
        "short_label": "ON RRP",
        "description": "隔夜逆回购工具使用量",
        "unit_label": "百万美元",
    },
    "liquidity:nyfed_rrp": {
        "label": "NY Fed 逆回购操作",
        "short_label": "NYFed RRP",
        "description": "纽约联储逆回购操作量",
        "unit_label": "百万美元",
    },
    "liquidity:reserve_balances": {
        "label": "银行准备金余额",
        "short_label": "准备金",
        "description": "银行体系准备金流动性缓冲",
        "unit_label": "百万美元",
    },
    "liquidity:sofr": {
        "label": "SOFR",
        "short_label": "SOFR",
        "description": "有担保隔夜融资利率",
        "unit_label": "%",
    },
    "liquidity:srf": {
        "label": "常设回购便利",
        "short_label": "SRF",
        "description": "纽约联储常设回购便利操作量",
        "unit_label": "百万美元",
    },
    "liquidity:tga": {
        "label": "财政部现金账户",
        "short_label": "TGA",
        "description": "美国财政部在美联储现金余额",
        "unit_label": "百万美元",
    },
    "positioning:sp500_net_noncommercial": {
        "label": "标普500 非商业净持仓",
        "short_label": "SPX 持仓",
        "description": "CFTC 标普500 非商业净持仓",
        "unit_label": "张",
    },
    "rates:10y2y": {
        "label": "10年-2年美债利差",
        "short_label": "10Y-2Y",
        "description": "美国收益率曲线斜率",
        "unit_label": "%",
    },
    "rates:10y3m": {
        "label": "10年-3个月美债利差",
        "short_label": "10Y-3M",
        "description": "美国期限利差与衰退压力代理",
        "unit_label": "%",
    },
    "rates:dgs1mo": {
        "label": "1个月美债收益率",
        "short_label": "1M",
        "description": "美国1个月国债收益率",
        "unit_label": "%",
    },
    "rates:dgs3mo": {
        "label": "3个月美债收益率",
        "short_label": "3M",
        "description": "美国3个月国债收益率",
        "unit_label": "%",
    },
    "rates:dgs6mo": {
        "label": "6个月美债收益率",
        "short_label": "6M",
        "description": "美国6个月国债收益率",
        "unit_label": "%",
    },
    "rates:dgs1": {
        "label": "1年期美债收益率",
        "short_label": "1Y",
        "description": "美国1年期国债收益率",
        "unit_label": "%",
    },
    "rates:dgs10": {
        "label": "10年期美债收益率",
        "short_label": "10Y",
        "description": "美国长期无风险利率基准",
        "unit_label": "%",
    },
    "rates:dgs2": {
        "label": "2年期美债收益率",
        "short_label": "2Y",
        "description": "政策预期敏感的短端美债收益率",
        "unit_label": "%",
    },
    "rates:dgs3": {
        "label": "3年期美债收益率",
        "short_label": "3Y",
        "description": "美国3年期国债收益率",
        "unit_label": "%",
    },
    "rates:dgs30": {
        "label": "30年期美债收益率",
        "short_label": "30Y",
        "description": "美国超长端无风险利率基准",
        "unit_label": "%",
    },
    "rates:dgs5": {
        "label": "5年期美债收益率",
        "short_label": "5Y",
        "description": "美国中端美债收益率",
        "unit_label": "%",
    },
    "rates:dgs7": {
        "label": "7年期美债收益率",
        "short_label": "7Y",
        "description": "美国7年期国债收益率",
        "unit_label": "%",
    },
    "rates:dgs20": {
        "label": "20年期美债收益率",
        "short_label": "20Y",
        "description": "美国20年期国债收益率",
        "unit_label": "%",
    },
    "rates:real_10y": {
        "label": "10年期实际利率",
        "short_label": "10Y Real",
        "description": "美国10年期 TIPS 实际收益率",
        "unit_label": "%",
    },
    "vol:vix": {
        "label": "VIX",
        "short_label": "VIX",
        "description": "标普500 隐含波动率压力",
        "unit_label": "点",
    },
    "vol:vix3m": {
        "label": "3个月 VIX",
        "short_label": "VIX3M",
        "description": "CBOE 3个月波动率指数",
        "unit_label": "点",
    },
    "asset:bnd": {
        "label": "美国综合债 ETF",
        "short_label": "BND",
        "description": "美国综合债券 ETF",
        "unit_label": "美元",
    },
    "asset:cper": {"label": "铜 ETF", "short_label": "CPER", "description": "铜价格代理 ETF", "unit_label": "美元"},
    "asset:dia": {"label": "道指 ETF", "short_label": "DIA", "description": "道琼斯工业指数 ETF", "unit_label": "美元"},
    "asset:eem": {
        "label": "新兴市场 ETF",
        "short_label": "EEM",
        "description": "新兴市场股票代理",
        "unit_label": "美元",
    },
    "asset:efa": {
        "label": "发达市场 ETF",
        "short_label": "EFA",
        "description": "美国以外发达市场股票代理",
        "unit_label": "美元",
    },
    "asset:fxe": {"label": "欧元 ETF", "short_label": "FXE", "description": "欧元可交易代理", "unit_label": "美元"},
    "asset:fxy": {"label": "日元 ETF", "short_label": "FXY", "description": "日元可交易代理", "unit_label": "美元"},
    "asset:jnk": {
        "label": "高收益债 ETF",
        "short_label": "JNK",
        "description": "高收益债 ETF 代理",
        "unit_label": "美元",
    },
    "asset:nasdaq": {
        "label": "纳斯达克综合指数",
        "short_label": "Nasdaq",
        "description": "纳斯达克综合指数",
        "unit_label": "点",
    },
    "asset:slv": {"label": "白银 ETF", "short_label": "SLV", "description": "白银价格代理", "unit_label": "美元"},
    "asset:tip": {"label": "TIPS ETF", "short_label": "TIP", "description": "通胀保值债券 ETF", "unit_label": "美元"},
    "asset:ung": {"label": "天然气 ETF", "short_label": "UNG", "description": "天然气价格代理", "unit_label": "美元"},
    "asset:uup": {"label": "美元 ETF", "short_label": "UUP", "description": "美元指数可交易代理", "unit_label": "美元"},
    "commodity:brent": {
        "label": "布伦特原油",
        "short_label": "Brent",
        "description": "布伦特原油现货价格",
        "unit_label": "美元/桶",
    },
    "commodity:natgas": {
        "label": "亨利港天然气",
        "short_label": "NatGas",
        "description": "美国天然气现货价格",
        "unit_label": "美元",
    },
    "consumer:pce_nominal": {
        "label": "名义 PCE",
        "short_label": "PCE",
        "description": "美国名义个人消费支出",
        "unit_label": "十亿美元",
    },
    "consumer:pce_real": {
        "label": "实际 PCE",
        "short_label": "Real PCE",
        "description": "美国实际个人消费支出",
        "unit_label": "十亿美元",
    },
    "consumer:saving_rate": {
        "label": "个人储蓄率",
        "short_label": "Savings",
        "description": "美国个人储蓄率",
        "unit_label": "%",
    },
    "credit:a_oas": {
        "label": "A 信用利差",
        "short_label": "A OAS",
        "description": "美国 A 级公司债 OAS",
        "unit_label": "%",
    },
    "credit:aa_oas": {
        "label": "AA 信用利差",
        "short_label": "AA OAS",
        "description": "美国 AA 级公司债 OAS",
        "unit_label": "%",
    },
    "credit:aaa_oas": {
        "label": "AAA 信用利差",
        "short_label": "AAA OAS",
        "description": "美国 AAA 级公司债 OAS",
        "unit_label": "%",
    },
    "credit:anfci": {
        "label": "调整后 NFCI",
        "short_label": "ANFCI",
        "description": "芝加哥联储调整后金融条件指数",
        "unit_label": "指数",
    },
    "credit:nfci": {
        "label": "NFCI",
        "short_label": "NFCI",
        "description": "芝加哥联储金融条件指数",
        "unit_label": "指数",
    },
    "credit:stl_stress": {
        "label": "圣路易斯金融压力",
        "short_label": "STLFSI",
        "description": "圣路易斯联储金融压力指数",
        "unit_label": "指数",
    },
    "economy:gdp_nominal": {
        "label": "名义 GDP",
        "short_label": "GDP",
        "description": "美国名义国内生产总值",
        "unit_label": "十亿美元",
    },
    "economy:housing_starts": {
        "label": "新屋开工",
        "short_label": "Housing",
        "description": "美国新屋开工数",
        "unit_label": "千套",
    },
    "economy:industrial_production": {
        "label": "工业生产",
        "short_label": "IndProd",
        "description": "美国工业生产指数",
        "unit_label": "指数",
    },
    "fed:dff": {
        "label": "日度联邦基金利率",
        "short_label": "DFF",
        "description": "日度有效联邦基金利率",
        "unit_label": "%",
    },
    "fx:fred_eurusd": {
        "label": "FRED 欧元汇率",
        "short_label": "EURUSD",
        "description": "FRED 欧元兑美元汇率",
        "unit_label": "汇率",
    },
    "fx:fred_gbpusd": {
        "label": "FRED 英镑汇率",
        "short_label": "GBPUSD",
        "description": "FRED 英镑兑美元汇率",
        "unit_label": "汇率",
    },
    "fx:fred_usdcny": {
        "label": "FRED 美元兑人民币",
        "short_label": "USDCNY",
        "description": "FRED 人民币兑美元汇率",
        "unit_label": "汇率",
    },
    "fx:fred_usdjpy": {
        "label": "FRED 美元兑日元",
        "short_label": "USDJPY",
        "description": "FRED 日元兑美元汇率",
        "unit_label": "汇率",
    },
    "inflation:5y_breakeven": {
        "label": "5年通胀盈亏平衡",
        "short_label": "5Y BEI",
        "description": "5年期通胀补偿",
        "unit_label": "%",
    },
    "inflation:core_pce": {
        "label": "核心 PCE",
        "short_label": "Core PCE",
        "description": "核心个人消费支出价格指数",
        "unit_label": "指数",
    },
    "inflation:gdp_deflator": {
        "label": "GDP 平减指数",
        "short_label": "GDP Deflator",
        "description": "GDP 隐含价格平减指数",
        "unit_label": "指数",
    },
    "inflation:mich_1y_expectation": {
        "label": "密歇根1年通胀预期",
        "short_label": "MICH",
        "description": "密歇根大学1年通胀预期",
        "unit_label": "%",
    },
    "inflation:pce": {
        "label": "PCE 价格指数",
        "short_label": "PCEPI",
        "description": "个人消费支出价格指数",
        "unit_label": "指数",
    },
    "labor:job_openings": {
        "label": "职位空缺",
        "short_label": "JOLTS",
        "description": "美国非农职位空缺",
        "unit_label": "千人",
    },
    "labor:participation": {
        "label": "劳动参与率",
        "short_label": "CIVPART",
        "description": "美国劳动参与率",
        "unit_label": "%",
    },
    "rates:real_30y": {
        "label": "30年期实际利率",
        "short_label": "30Y Real",
        "description": "美国30年期 TIPS 实际收益率",
        "unit_label": "%",
    },
    "rates:real_5y": {
        "label": "5年期实际利率",
        "short_label": "5Y Real",
        "description": "美国5年期 TIPS 实际收益率",
        "unit_label": "%",
    },
    "vol:evz": {"label": "欧元波动率", "short_label": "EVZ", "description": "欧元隐含波动率指数", "unit_label": "点"},
    "vol:gvz": {
        "label": "黄金波动率",
        "short_label": "GVZ",
        "description": "黄金 ETF 隐含波动率指数",
        "unit_label": "点",
    },
    "vol:ovx": {
        "label": "原油波动率",
        "short_label": "OVX",
        "description": "原油 ETF 隐含波动率指数",
        "unit_label": "点",
    },
    "vol:rvx": {
        "label": "小盘波动率",
        "short_label": "RVX",
        "description": "罗素2000 隐含波动率指数",
        "unit_label": "点",
    },
    "vol:vxn": {
        "label": "纳指波动率",
        "short_label": "VXN",
        "description": "纳指100 隐含波动率指数",
        "unit_label": "点",
    },
}

__all__ = [
    "MACRO_CONCEPT_METADATA",
    "MACRO_CORE_CONCEPTS",
    "MACRO_HISTORY_REQUIRED_CONCEPTS",
    "MACRO_HISTORY_REQUIRED_POINTS_BY_CONCEPT",
    "MACRO_MIN_CHART_POINTS",
    "MACRO_MODULE_VIEW_VERSION",
    "MACRO_OPTIONAL_HISTORY_CONCEPTS",
    "MACRO_PROVIDER_SERIES_SOURCE_PRIORITY",
    "MACRO_PROVIDER_SERIES_TO_CONCEPT",
    "MACRO_REQUIRED_DELTA_POINTS",
    "MACRO_REQUIRED_STAT_POINTS",
    "MACRO_VIEW_HISTORY_LIMIT_PER_SERIES",
    "MACRO_VIEW_HISTORY_LOOKBACK_DAYS",
    "MACRO_VIEW_PROJECTION_VERSION",
]
