# tests/contract/test_openapi_drift.py
"""Contract test: regenerate OpenAPI + frontend types and assert no drift.

If this test fails, run `make regen-contract` to update the committed artefacts,
then commit the resulting diff so reviewers can see the schema change.

Note on types layout
--------------------
web/src/lib/types/openapi.ts  — auto-generated by openapi-typescript; only
                                OpenAPI path/component/operation interfaces live here.
web/src/api/types.ts          — temporary hand-authored domain types until the
                                frontend facade moves fully to generated contracts.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "docs" / "generated" / "openapi.json"
OPENAPI_TS_PATH = ROOT / "web" / "src" / "lib" / "types" / "openapi.ts"
FRONTEND_CONTRACTS_PATH = ROOT / "web" / "src" / "lib" / "types" / "frontend-contracts.ts"


@pytest.mark.contract
def test_openapi_json_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate openapi.json into a tmp dir and compare bytes with the committed one."""
    from gmgn_twitter_intel.app.runtime.app import create_app
    from gmgn_twitter_intel.platform.config.settings import Settings

    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings, start_collector=False)
    fresh = json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"
    committed = OPENAPI_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        diff_path = tmp_path / "openapi.fresh.json"
        diff_path.write_text(fresh, encoding="utf-8")
        pytest.fail(
            "OpenAPI schema drifted from docs/generated/openapi.json.\n"
            f"Run `make regen-contract` to update the committed artefacts.\n"
            f"Fresh schema written to {diff_path} for inspection."
        )


@pytest.mark.contract
def test_openapi_ts_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate web/src/lib/types/openapi.ts and compare with the committed one."""
    fresh_path = tmp_path / "openapi.ts"
    result = subprocess.run(
        [
            "npx",
            "openapi-typescript",
            str(OPENAPI_PATH),
            "-o",
            str(fresh_path),
        ],
        cwd=str(ROOT / "web"),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(
            "openapi-typescript invocation failed.\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}\n"
            "Make sure `cd web && npm install` has run."
        )
    fresh = fresh_path.read_text(encoding="utf-8")
    committed = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        pytest.fail(
            f"Frontend OpenAPI types drifted from {OPENAPI_TS_PATH.relative_to(ROOT)}.\n"
            "Run `make regen-contract` to update the committed artefacts."
        )


@pytest.mark.contract
def test_signal_pulse_item_schema_matches_runtime_payload_keys() -> None:
    """The OpenAPI item contract should expose the fields emitted by SignalPulseService."""
    schema = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    props = schema["components"]["schemas"]["SignalPulseItem"]["properties"]

    expected = {
        "candidate_id",
        "candidate_type",
        "subject_key",
        "subject",
        "target_type",
        "target_id",
        "symbol",
        "window",
        "scope",
        "pulse_status",
        "verdict",
        "social_phase",
        "candidate_score",
        "score_band",
        "gate_reasons",
        "risk_reasons",
        "last_edge_events",
        "evidence_event_ids",
        "source_event_ids",
        "factor_snapshot",
        "decision",
        "gate",
        "fact_card",
        "agent_run_id",
        "pulse_version",
        "gate_version",
        "prompt_version",
        "schema_version",
        "created_at_ms",
        "updated_at_ms",
        "playbooks",
        "stages",
    }
    assert expected <= set(props)
    assert "status" not in props
    assert "target" not in props

    decision = schema["components"]["schemas"]["SignalPulseDecision"]
    assert {
        "route",
        "recommendation",
        "confidence",
        "summary_zh",
        "abstain_reason",
        "narrative_archetype",
        "narrative_thesis_zh",
        "bull_view",
        "bear_view",
        "playbook",
        "evidence_event_ids",
        "evidence_event_urls",
        "invalidation_conditions",
        "residual_risks",
    } <= set(decision["required"])


@pytest.mark.contract
def test_signal_pulse_stages_schema_exposes_only_v2_stage_fields() -> None:
    """Signal Pulse public stages are v2-only; legacy DB stage rows stay internal."""
    from gmgn_twitter_intel.app.runtime.app import create_app
    from gmgn_twitter_intel.platform.config.settings import Settings

    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings, start_collector=False)
    schema = app.openapi()
    props = schema["components"]["schemas"]["SignalPulseStages"]["properties"]

    assert set(props) == {"investigator", "decision_maker", "research_only_gate"}
    assert schema["components"]["schemas"]["SignalPulseStages"]["additionalProperties"] is False


@pytest.mark.contract
def test_signal_pulse_stages_openapi_type_has_no_index_signature() -> None:
    """Generated OpenAPI TS must not allow arbitrary stage keys on SignalPulseStages."""
    text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    section = text.split("/** SignalPulseStages */", 1)[1].split("/** SocialEventDetail */", 1)[0]

    assert "[key: string]" not in section


@pytest.mark.contract
def test_market_candles_contract_has_no_legacy_market_payload_field() -> None:
    """Search and timeline contracts expose market_candles only."""
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    openapi_ts_text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    frontend_contracts_text = FRONTEND_CONTRACTS_PATH.read_text(encoding="utf-8")
    legacy_field = "market_overlay"

    assert "market_candles" in openapi_text
    assert "market_candles" in openapi_ts_text
    assert "market_candles" in frontend_contracts_text
    assert legacy_field not in openapi_text
    assert legacy_field not in openapi_ts_text
    assert legacy_field not in frontend_contracts_text
