from __future__ import annotations

from dataclasses import dataclass


class UnsupportedMacroModuleError(ValueError):
    def __init__(self, module_id: str) -> None:
        super().__init__(f"Unsupported macro module: {module_id}")
        self.code = "unsupported_macro_module"
        self.module_id = module_id


@dataclass(frozen=True)
class MacroChartSpec:
    chart_id: str
    concept_keys: tuple[str, ...] = ()


@dataclass(frozen=True)
class MacroTableSpec:
    table_id: str
    concept_keys: tuple[str, ...] = ()


@dataclass(frozen=True)
class MacroModuleConfig:
    module_id: str
    route_path: str
    title: str
    subtitle: str
    question: str
    section: str
    required_concepts: tuple[str, ...]
    optional_concepts: tuple[str, ...]
    chart_specs: tuple[MacroChartSpec, ...]
    table_specs: tuple[MacroTableSpec, ...]
    gap_codes: tuple[str, ...]
    related_routes: tuple[str, ...]


MACRO_MODULE_IDS = (
    "overview",
    "assets",
    "assets/equities",
    "assets/bonds",
    "assets/commodities",
    "assets/fx",
    "assets/crypto",
    "assets/crypto-derivatives",
    "rates",
    "rates/fed-funds",
    "rates/yield-curve",
    "rates/auctions",
    "rates/real-rates",
    "rates/expectations",
    "fed",
    "fed/statements",
    "fed/speeches",
    "liquidity",
    "liquidity/transmission-chain",
    "liquidity/fed-balance-sheet",
    "liquidity/operations",
    "liquidity/rrp-tga",
    "liquidity/reserves",
    "liquidity/global-dollar",
    "liquidity/subsurface",
    "economy",
    "economy/gdp",
    "economy/employment",
    "economy/inflation",
    "economy/consumer",
    "volatility",
    "volatility/dashboard",
    "volatility/vix",
    "credit",
    "credit/cds",
    "credit/stress",
)


_MODULE_CONFIGS = {
    "overview": MacroModuleConfig(
        module_id="overview",
        route_path="/macro",
        title="宏观总览",
        subtitle="跨资产、利率、波动率与信用链条",
        question="宏观链条现在是在支持风险资产，还是提示降风险？",
        section="overview",
        required_concepts=(),
        optional_concepts=("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas"),
        chart_specs=(MacroChartSpec("macro_regime", ("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas")),),
        table_specs=(MacroTableSpec("panel_scorecard", ("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas")),),
        gap_codes=(),
        related_routes=("/macro/assets", "/macro/rates", "/macro/liquidity", "/macro/volatility", "/macro/credit"),
    ),
    "assets": MacroModuleConfig(
        module_id="assets",
        route_path="/macro/assets",
        title="资产联动",
        subtitle="跨资产风险偏好与加密确认",
        question="跨资产信号是在确认 risk-on，还是开始转向防守？",
        section="assets",
        required_concepts=(),
        optional_concepts=("asset:spx", "asset:spy", "asset:qqq", "asset:iwm", "asset:tlt", "crypto:btc"),
        chart_specs=(MacroChartSpec("asset_proxy_performance", ("asset:spy", "asset:qqq", "asset:tlt")),),
        table_specs=(MacroTableSpec("asset_proxy_snapshot", ("asset:spy", "asset:qqq", "asset:tlt")),),
        gap_codes=(),
        related_routes=(
            "/macro/assets/equities",
            "/macro/assets/bonds",
            "/macro/assets/commodities",
            "/macro/assets/fx",
            "/macro/assets/crypto",
        ),
    ),
    "assets/equities": MacroModuleConfig(
        module_id="assets/equities",
        route_path="/macro/assets/equities",
        title="美股风险",
        subtitle="SPX / QQQ / IWM 风险偏好确认",
        question="美股领导力是在确认加密 beta，还是开始拖累风险资产？",
        section="assets",
        required_concepts=("asset:spx",),
        optional_concepts=("asset:spy", "asset:qqq", "asset:iwm"),
        chart_specs=(MacroChartSpec("equity_proxy_performance", ("asset:spx", "asset:spy", "asset:qqq", "asset:iwm")),),
        table_specs=(MacroTableSpec("equity_proxy_snapshot", ("asset:spx", "asset:spy", "asset:qqq", "asset:iwm")),),
        gap_codes=("equity_breadth_missing", "equity_options_gex_missing"),
        related_routes=("/macro/assets", "/macro/assets/bonds", "/macro/volatility"),
    ),
    "assets/bonds": MacroModuleConfig(
        module_id="assets/bonds",
        route_path="/macro/assets/bonds",
        title="债券资产",
        subtitle="久期压力与信用确认",
        question="债券市场是在释放久期压力，还是确认避险需求？",
        section="assets",
        required_concepts=("asset:tlt",),
        optional_concepts=("asset:hyg", "asset:lqd", "credit:hy_oas", "credit:ig_oas"),
        chart_specs=(MacroChartSpec("bond_proxy_performance", ("asset:tlt", "asset:hyg", "asset:lqd")),),
        table_specs=(MacroTableSpec("bond_proxy_snapshot", ("asset:tlt", "asset:hyg", "asset:lqd")),),
        gap_codes=("move_index_missing",),
        related_routes=("/macro/assets", "/macro/rates", "/macro/credit"),
    ),
    "assets/commodities": MacroModuleConfig(
        module_id="assets/commodities",
        route_path="/macro/assets/commodities",
        title="商品冲击",
        subtitle="原油、黄金与通胀脉冲",
        question="商品价格是在制造通胀压力，还是只是局部供需扰动？",
        section="assets",
        required_concepts=("commodity:wti",),
        optional_concepts=("asset:gld", "asset:uso"),
        chart_specs=(MacroChartSpec("commodity_proxy_performance", ("commodity:wti", "asset:gld", "asset:uso")),),
        table_specs=(MacroTableSpec("commodity_proxy_snapshot", ("commodity:wti", "asset:gld", "asset:uso")),),
        gap_codes=(),
        related_routes=("/macro/assets", "/macro/assets/fx"),
    ),
    "assets/fx": MacroModuleConfig(
        module_id="assets/fx",
        route_path="/macro/assets/fx",
        title="美元压力",
        subtitle="DXY 与广义美元流动性",
        question="美元是在收紧离岸流动性，还是给风险资产让路？",
        section="assets",
        required_concepts=("fx:dxy",),
        optional_concepts=("fx:broad_dollar",),
        chart_specs=(MacroChartSpec("fx_proxy_performance", ("fx:dxy", "fx:broad_dollar")),),
        table_specs=(MacroTableSpec("fx_proxy_snapshot", ("fx:dxy", "fx:broad_dollar")),),
        gap_codes=(),
        related_routes=("/macro/assets", "/macro/liquidity"),
    ),
    "assets/crypto": MacroModuleConfig(
        module_id="assets/crypto",
        route_path="/macro/assets/crypto",
        title="加密资产",
        subtitle="BTC / ETH 宏观 beta",
        question="BTC/ETH 是在确认宏观 risk-on，还是只是自身波动？",
        section="assets",
        required_concepts=("crypto:btc",),
        optional_concepts=("crypto:eth",),
        chart_specs=(MacroChartSpec("crypto_proxy_performance", ("crypto:btc", "crypto:eth")),),
        table_specs=(MacroTableSpec("crypto_proxy_snapshot", ("crypto:btc", "crypto:eth")),),
        gap_codes=("crypto_options_missing",),
        related_routes=("/macro/assets", "/macro/assets/crypto-derivatives"),
    ),
    "assets/crypto-derivatives": MacroModuleConfig(
        module_id="assets/crypto-derivatives",
        route_path="/macro/assets/crypto-derivatives",
        title="加密衍生品",
        subtitle="CEX OI、资金费率与杠杆状态",
        question="合约杠杆是在放大趋势，还是制造挤仓风险？",
        section="assets",
        required_concepts=(),
        optional_concepts=("crypto:btc", "crypto:eth"),
        chart_specs=(MacroChartSpec("crypto_derivative_context", ("crypto:btc", "crypto:eth")),),
        table_specs=(MacroTableSpec("cex_perp_board", ()),),
        gap_codes=("crypto_options_missing", "basis_missing", "etf_flows_missing"),
        related_routes=("/macro/assets/crypto", "/macro/assets"),
    ),
    "rates": MacroModuleConfig(
        module_id="rates",
        route_path="/macro/rates",
        title="利率定价",
        subtitle="曲线、实际利率与估值压力",
        question="利率曲线是在释放风险偏好，还是继续压制估值？",
        section="rates",
        required_concepts=("rates:dgs2", "rates:dgs10"),
        optional_concepts=(
            "rates:dgs3mo",
            "rates:dgs1",
            "rates:dgs5",
            "rates:dgs30",
            "rates:10y2y",
            "rates:10y3m",
        ),
        chart_specs=(
            MacroChartSpec("rates_curve", ("rates:dgs3mo", "rates:dgs2", "rates:dgs5", "rates:dgs10", "rates:dgs30")),
        ),
        table_specs=(MacroTableSpec("rates_snapshot", ("rates:dgs2", "rates:dgs10", "rates:10y2y", "rates:10y3m")),),
        gap_codes=("move_index_missing",),
        related_routes=(
            "/macro/rates/fed-funds",
            "/macro/rates/yield-curve",
            "/macro/rates/auctions",
            "/macro/rates/expectations",
            "/macro/rates/real-rates",
        ),
    ),
    "rates/fed-funds": MacroModuleConfig(
        module_id="rates/fed-funds",
        route_path="/macro/rates/fed-funds",
        title="联邦基金与走廊",
        subtitle="目标区间、EFFR、IORB、SOFR 与月均联邦基金",
        question="政策走廊是否稳定，隔夜融资是否溢出目标区间？",
        section="rates",
        required_concepts=("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb"),
        optional_concepts=("fed:fedfunds", "fed:sofr_30d", "liquidity:sofr"),
        chart_specs=(
            MacroChartSpec(
                "fed_funds_corridor",
                (
                    "fed:target_upper",
                    "fed:target_lower",
                    "fed:effr",
                    "fed:iorb",
                    "liquidity:sofr",
                    "fed:sofr_30d",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "fed_funds_snapshot",
                ("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb", "liquidity:sofr", "fed:sofr_30d"),
            ),
        ),
        gap_codes=("fomc_calendar_missing",),
        related_routes=("/macro/fed", "/macro/liquidity/subsurface", "/macro/rates/expectations"),
    ),
    "rates/yield-curve": MacroModuleConfig(
        module_id="rates/yield-curve",
        route_path="/macro/rates/yield-curve",
        title="收益率曲线",
        subtitle="1M 到 30Y 的曲线形态与期限利差",
        question="曲线形态是在交易衰退压力，还是交易期限溢价？",
        section="rates",
        required_concepts=("rates:dgs2", "rates:dgs10"),
        optional_concepts=(
            "rates:dgs1mo",
            "rates:dgs3mo",
            "rates:dgs6mo",
            "rates:dgs1",
            "rates:dgs3",
            "rates:dgs5",
            "rates:dgs7",
            "rates:dgs20",
            "rates:dgs30",
            "rates:10y2y",
            "rates:10y3m",
        ),
        chart_specs=(
            MacroChartSpec(
                "yield_curve",
                (
                    "rates:dgs1mo",
                    "rates:dgs3mo",
                    "rates:dgs6mo",
                    "rates:dgs1",
                    "rates:dgs2",
                    "rates:dgs3",
                    "rates:dgs5",
                    "rates:dgs7",
                    "rates:dgs10",
                    "rates:dgs20",
                    "rates:dgs30",
                ),
            ),
        ),
        table_specs=(MacroTableSpec("curve_spreads", ("rates:10y2y", "rates:10y3m", "rates:dgs10", "rates:dgs30")),),
        gap_codes=(),
        related_routes=("/macro/rates", "/macro/rates/real-rates", "/macro/rates/expectations"),
    ),
    "rates/auctions": MacroModuleConfig(
        module_id="rates/auctions",
        route_path="/macro/rates/auctions",
        title="国债拍卖",
        subtitle="公共收益率代理与缺失的拍卖结果数据",
        question="拍卖供给压力是否体现在曲线和长端收益率上？",
        section="rates",
        required_concepts=("rates:dgs2", "rates:dgs10", "rates:dgs30"),
        optional_concepts=("rates:dgs3", "rates:dgs7", "rates:dgs20", "rates:10y2y"),
        chart_specs=(MacroChartSpec("auction_curve_proxy", ("rates:dgs2", "rates:dgs7", "rates:dgs10", "rates:dgs30")),),
        table_specs=(
            MacroTableSpec("auction_rate_proxy_table", ("rates:dgs2", "rates:dgs7", "rates:dgs10", "rates:dgs30")),
        ),
        gap_codes=("treasury_auction_calendar_missing", "treasury_auction_results_missing"),
        related_routes=("/macro/rates/yield-curve", "/macro/rates/expectations", "/macro/liquidity"),
    ),
    "rates/real-rates": MacroModuleConfig(
        module_id="rates/real-rates",
        route_path="/macro/rates/real-rates",
        title="实际利率",
        subtitle="TIPS 实际收益率与通胀补偿",
        question="实际利率是在压制成长估值，还是通胀预期主导？",
        section="rates",
        required_concepts=("rates:real_10y",),
        optional_concepts=("inflation:10y_breakeven", "inflation:5y5y_forward"),
        chart_specs=(MacroChartSpec("real_rates", ("rates:real_10y", "inflation:10y_breakeven")),),
        table_specs=(MacroTableSpec("real_rates_snapshot", ("rates:real_10y", "inflation:10y_breakeven")),),
        gap_codes=(),
        related_routes=("/macro/rates", "/macro/rates/yield-curve", "/macro/economy/inflation"),
    ),
    "rates/expectations": MacroModuleConfig(
        module_id="rates/expectations",
        route_path="/macro/rates/expectations",
        title="政策预期",
        subtitle="短端利率、目标区间与市场代理",
        question="市场是否在重新定价降息/维持/加息路径？",
        section="rates",
        required_concepts=("rates:dgs1", "rates:dgs2", "fed:target_upper", "fed:target_lower"),
        optional_concepts=("fed:fedfunds", "inflation:5y5y_forward", "rates:dgs3mo"),
        chart_specs=(
            MacroChartSpec(
                "policy_expectations_proxy",
                ("rates:dgs3mo", "rates:dgs1", "rates:dgs2", "fed:target_upper", "fed:target_lower"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "policy_expectations_table",
                ("rates:dgs3mo", "rates:dgs1", "rates:dgs2", "fed:target_upper", "fed:fedfunds"),
            ),
        ),
        gap_codes=("fed_funds_futures_missing", "fomc_probability_feed_missing"),
        related_routes=("/macro/rates/fed-funds", "/macro/fed", "/macro/rates/yield-curve"),
    ),
    "fed": MacroModuleConfig(
        module_id="fed",
        route_path="/macro/fed",
        title="美联储走廊",
        subtitle="政策利率、EFFR、IORB 与 SOFR",
        question="政策走廊是否稳定，还是隔夜融资开始出现压力？",
        section="fed",
        required_concepts=("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb"),
        optional_concepts=("liquidity:sofr",),
        chart_specs=(
            MacroChartSpec(
                "fed_corridor", ("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb", "liquidity:sofr")
            ),
        ),
        table_specs=(
            MacroTableSpec("fed_corridor_snapshot", ("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb")),
        ),
        gap_codes=("fed_calendar_missing", "fed_speeches_missing", "fed_statement_text_missing"),
        related_routes=("/macro/rates/fed-funds", "/macro/fed/statements", "/macro/fed/speeches", "/macro/liquidity"),
    ),
    "fed/statements": MacroModuleConfig(
        module_id="fed/statements",
        route_path="/macro/fed/statements",
        title="FOMC 声明与会议文本",
        subtitle="只展示政策利率代理和文本数据可用性",
        question="声明文本源是否已接入，政策利率是否发生阶跃？",
        section="fed",
        required_concepts=("fed:target_upper", "fed:target_lower", "fed:effr"),
        optional_concepts=("fed:fedfunds", "rates:dgs2", "rates:dgs10"),
        chart_specs=(
            MacroChartSpec("fed_statement_policy_proxy", ("fed:target_upper", "fed:target_lower", "fed:effr", "fed:fedfunds")),
        ),
        table_specs=(MacroTableSpec("fed_statement_proxy_table", ("fed:target_upper", "fed:target_lower", "fed:effr", "rates:dgs2")),),
        gap_codes=("fed_statement_text_missing", "fomc_minutes_missing", "fomc_calendar_missing"),
        related_routes=("/macro/fed", "/macro/fed/speeches", "/macro/rates/expectations"),
    ),
    "fed/speeches": MacroModuleConfig(
        module_id="fed/speeches",
        route_path="/macro/fed/speeches",
        title="美联储讲话",
        subtitle="政策沟通数据可用性与市场代理",
        question="讲话源是否接入，短端市场是否同步反应？",
        section="fed",
        required_concepts=("fed:effr", "rates:dgs2"),
        optional_concepts=("fed:target_upper", "fed:target_lower", "rates:dgs10", "vol:vix"),
        chart_specs=(MacroChartSpec("fed_speeches_market_proxy", ("rates:dgs2", "rates:dgs10", "vol:vix")),),
        table_specs=(MacroTableSpec("fed_speeches_proxy_table", ("fed:effr", "rates:dgs2", "rates:dgs10", "vol:vix")),),
        gap_codes=("fed_speeches_missing", "fed_speaker_calendar_missing"),
        related_routes=("/macro/fed", "/macro/fed/statements", "/macro/rates/expectations"),
    ),
    "liquidity": MacroModuleConfig(
        module_id="liquidity",
        route_path="/macro/liquidity",
        title="美元流动性",
        subtitle="Fed 资产、RRP、TGA、准备金与 SOFR",
        question="美元流动性是在扩张风险承载，还是抽走市场缓冲？",
        section="liquidity",
        required_concepts=("liquidity:fed_assets", "liquidity:on_rrp", "liquidity:tga"),
        optional_concepts=("liquidity:reserve_balances", "liquidity:sofr"),
        chart_specs=(MacroChartSpec("liquidity_stack", ("liquidity:fed_assets", "liquidity:on_rrp", "liquidity:tga")),),
        table_specs=(
            MacroTableSpec("liquidity_snapshot", ("liquidity:fed_assets", "liquidity:on_rrp", "liquidity:tga")),
        ),
        gap_codes=(),
        related_routes=(
            "/macro/liquidity/transmission-chain",
            "/macro/liquidity/fed-balance-sheet",
            "/macro/liquidity/rrp-tga",
            "/macro/liquidity/reserves",
            "/macro/liquidity/subsurface",
        ),
    ),
    "liquidity/transmission-chain": MacroModuleConfig(
        module_id="liquidity/transmission-chain",
        route_path="/macro/liquidity/transmission-chain",
        title="流动性传导链",
        subtitle="资产负债表到融资市场的传导",
        question="流动性压力有没有传导到融资利率和风险资产？",
        section="liquidity",
        required_concepts=("liquidity:fed_assets", "liquidity:sofr"),
        optional_concepts=("liquidity:reserve_balances", "liquidity:on_rrp", "liquidity:tga"),
        chart_specs=(MacroChartSpec("transmission_chain", ("liquidity:fed_assets", "liquidity:sofr")),),
        table_specs=(MacroTableSpec("transmission_nodes", ()),),
        gap_codes=(),
        related_routes=("/macro/liquidity", "/macro/liquidity/subsurface", "/macro/fed", "/macro/rates"),
    ),
    "liquidity/fed-balance-sheet": MacroModuleConfig(
        module_id="liquidity/fed-balance-sheet",
        route_path="/macro/liquidity/fed-balance-sheet",
        title="美联储资产负债表",
        subtitle="总资产、准备金与 QT 传导",
        question="资产负债表是在扩张还是收缩风险资产缓冲？",
        section="liquidity",
        required_concepts=("liquidity:fed_assets", "liquidity:reserve_balances"),
        optional_concepts=("liquidity:on_rrp", "liquidity:tga"),
        chart_specs=(MacroChartSpec("fed_balance_sheet", ("liquidity:fed_assets", "liquidity:reserve_balances")),),
        table_specs=(MacroTableSpec("fed_balance_sheet_table", ("liquidity:fed_assets", "liquidity:reserve_balances", "liquidity:on_rrp", "liquidity:tga")),),
        gap_codes=(),
        related_routes=("/macro/liquidity", "/macro/liquidity/reserves", "/macro/liquidity/rrp-tga"),
    ),
    "liquidity/operations": MacroModuleConfig(
        module_id="liquidity/operations",
        route_path="/macro/liquidity/operations",
        title="公开市场操作",
        subtitle="RRP、SRF 与回购市场操作",
        question="纽约联储操作量是否提示短端资金压力？",
        section="liquidity",
        required_concepts=("liquidity:nyfed_rrp",),
        optional_concepts=("liquidity:srf", "liquidity:on_rrp", "liquidity:sofr", "fed:iorb"),
        chart_specs=(MacroChartSpec("nyfed_operations", ("liquidity:nyfed_rrp", "liquidity:srf", "liquidity:on_rrp")),),
        table_specs=(MacroTableSpec("nyfed_operations_table", ("liquidity:nyfed_rrp", "liquidity:srf", "liquidity:sofr", "fed:iorb")),),
        gap_codes=(),
        related_routes=("/macro/liquidity/rrp-tga", "/macro/liquidity/subsurface", "/macro/fed"),
    ),
    "liquidity/rrp-tga": MacroModuleConfig(
        module_id="liquidity/rrp-tga",
        route_path="/macro/liquidity/rrp-tga",
        title="RRP / TGA",
        subtitle="财政现金、逆回购与净流动性代理",
        question="TGA 与 RRP 是否正在吸收市场流动性？",
        section="liquidity",
        required_concepts=("liquidity:on_rrp", "liquidity:tga"),
        optional_concepts=("liquidity:fed_assets", "liquidity:sofr", "fed:iorb"),
        chart_specs=(MacroChartSpec("rrp_tga_stack", ("liquidity:on_rrp", "liquidity:tga", "liquidity:fed_assets")),),
        table_specs=(MacroTableSpec("rrp_tga_table", ("liquidity:on_rrp", "liquidity:tga", "liquidity:sofr", "fed:iorb")),),
        gap_codes=(),
        related_routes=("/macro/liquidity", "/macro/liquidity/fed-balance-sheet", "/macro/liquidity/subsurface"),
    ),
    "liquidity/reserves": MacroModuleConfig(
        module_id="liquidity/reserves",
        route_path="/macro/liquidity/reserves",
        title="银行准备金",
        subtitle="准备金余额与总资产",
        question="银行体系准备金缓冲是否在下降？",
        section="liquidity",
        required_concepts=("liquidity:reserve_balances",),
        optional_concepts=("liquidity:fed_assets", "liquidity:sofr", "fed:iorb"),
        chart_specs=(MacroChartSpec("reserve_balances", ("liquidity:reserve_balances", "liquidity:fed_assets")),),
        table_specs=(MacroTableSpec("reserve_balances_table", ("liquidity:reserve_balances", "liquidity:fed_assets", "liquidity:sofr")),),
        gap_codes=(),
        related_routes=("/macro/liquidity", "/macro/liquidity/fed-balance-sheet", "/macro/liquidity/subsurface"),
    ),
    "liquidity/global-dollar": MacroModuleConfig(
        module_id="liquidity/global-dollar",
        route_path="/macro/liquidity/global-dollar",
        title="全球美元",
        subtitle="广义美元、DXY 与主要汇率代理",
        question="美元压力是否在收紧全球风险资产流动性？",
        section="liquidity",
        required_concepts=("fx:broad_dollar", "fx:dxy"),
        optional_concepts=("fx:eurusd", "fx:usdjpy", "liquidity:sofr"),
        chart_specs=(MacroChartSpec("global_dollar_pressure", ("fx:broad_dollar", "fx:dxy", "fx:eurusd", "fx:usdjpy")),),
        table_specs=(MacroTableSpec("global_dollar_table", ("fx:broad_dollar", "fx:dxy", "fx:eurusd", "fx:usdjpy")),),
        gap_codes=("cross_currency_basis_missing", "global_dollar_funding_missing"),
        related_routes=("/macro/liquidity", "/macro/assets/fx", "/macro/liquidity/subsurface"),
    ),
    "liquidity/subsurface": MacroModuleConfig(
        module_id="liquidity/subsurface",
        route_path="/macro/liquidity/subsurface",
        title="资金面暗流",
        subtitle="SOFR、IORB、SRF 与短端压力代理",
        question="资金面压力是否从回购市场渗透到政策走廊？",
        section="liquidity",
        required_concepts=("liquidity:sofr", "fed:iorb"),
        optional_concepts=("fed:effr", "fed:sofr_30d", "liquidity:srf"),
        chart_specs=(MacroChartSpec("subsurface_funding", ("liquidity:sofr", "fed:iorb", "fed:effr", "fed:sofr_30d")),),
        table_specs=(MacroTableSpec("subsurface_funding_table", ("liquidity:sofr", "fed:iorb", "fed:effr", "fed:sofr_30d", "liquidity:srf")),),
        gap_codes=("repo_intraday_pressure_missing",),
        related_routes=("/macro/rates/fed-funds", "/macro/liquidity/operations", "/macro/fed"),
    ),
    "economy": MacroModuleConfig(
        module_id="economy",
        route_path="/macro/economy",
        title="经济数据",
        subtitle="增长、就业、通胀与消费四象限",
        question="经济数据是在支持软着陆，还是提示增长/通胀错配？",
        section="economy",
        required_concepts=("economy:gdp_real", "labor:unemployment", "inflation:cpi", "consumer:retail_sales"),
        optional_concepts=("labor:payrolls", "labor:initial_claims", "inflation:core_cpi", "consumer:umich_sentiment"),
        chart_specs=(
            MacroChartSpec("economy_four_pillar", ("labor:unemployment", "inflation:cpi", "consumer:retail_sales")),
        ),
        table_specs=(
            MacroTableSpec(
                "economy_four_pillar_table",
                (
                    "economy:gdp_real",
                    "labor:unemployment",
                    "labor:payrolls",
                    "labor:initial_claims",
                    "inflation:cpi",
                    "consumer:retail_sales",
                ),
            ),
        ),
        gap_codes=(),
        related_routes=(
            "/macro/economy/gdp",
            "/macro/economy/employment",
            "/macro/economy/inflation",
            "/macro/economy/consumer",
        ),
    ),
    "economy/gdp": MacroModuleConfig(
        module_id="economy/gdp",
        route_path="/macro/economy/gdp",
        title="GDP 增长",
        subtitle="实际 GDP 与增长代理",
        question="增长数据是否足够支撑风险资产盈利预期？",
        section="economy",
        required_concepts=("economy:gdp_real",),
        optional_concepts=("consumer:retail_sales", "labor:payrolls", "rates:dgs10"),
        chart_specs=(MacroChartSpec("real_gdp_history", ("economy:gdp_real", "consumer:retail_sales")),),
        table_specs=(MacroTableSpec("real_gdp_table", ("economy:gdp_real", "consumer:retail_sales", "labor:payrolls")),),
        gap_codes=("gdp_nowcast_missing",),
        related_routes=("/macro/economy", "/macro/economy/employment", "/macro/economy/consumer"),
    ),
    "economy/employment": MacroModuleConfig(
        module_id="economy/employment",
        route_path="/macro/economy/employment",
        title="就业市场",
        subtitle="失业率、非农与初请失业金",
        question="就业是在缓慢降温，还是触发增长风险？",
        section="economy",
        required_concepts=("labor:unemployment", "labor:payrolls", "labor:initial_claims"),
        optional_concepts=("fed:target_upper", "rates:dgs2"),
        chart_specs=(MacroChartSpec("employment_dashboard", ("labor:unemployment", "labor:payrolls", "labor:initial_claims")),),
        table_specs=(MacroTableSpec("employment_table", ("labor:unemployment", "labor:payrolls", "labor:initial_claims", "rates:dgs2")),),
        gap_codes=("jolts_missing", "average_hourly_earnings_missing"),
        related_routes=("/macro/economy", "/macro/economy/inflation", "/macro/rates/expectations"),
    ),
    "economy/inflation": MacroModuleConfig(
        module_id="economy/inflation",
        route_path="/macro/economy/inflation",
        title="通胀数据",
        subtitle="CPI、核心 CPI、PPI 与市场通胀补偿",
        question="通胀压力是否足以改变政策预期？",
        section="economy",
        required_concepts=("inflation:cpi", "inflation:core_cpi", "inflation:ppi"),
        optional_concepts=("inflation:10y_breakeven", "inflation:5y5y_forward"),
        chart_specs=(
            MacroChartSpec(
                "inflation_dashboard",
                ("inflation:cpi", "inflation:core_cpi", "inflation:ppi", "inflation:10y_breakeven"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "inflation_table",
                ("inflation:cpi", "inflation:core_cpi", "inflation:ppi", "inflation:10y_breakeven", "inflation:5y5y_forward"),
            ),
        ),
        gap_codes=("inflation_yoy_transform_missing",),
        related_routes=("/macro/economy", "/macro/rates/real-rates", "/macro/rates/expectations"),
    ),
    "economy/consumer": MacroModuleConfig(
        module_id="economy/consumer",
        route_path="/macro/economy/consumer",
        title="消费与信心",
        subtitle="零售销售与消费者信心",
        question="消费是否仍在支撑增长，还是开始转弱？",
        section="economy",
        required_concepts=("consumer:retail_sales", "consumer:umich_sentiment"),
        optional_concepts=("labor:unemployment", "inflation:cpi", "asset:spx"),
        chart_specs=(MacroChartSpec("consumer_dashboard", ("consumer:retail_sales", "consumer:umich_sentiment", "asset:spx")),),
        table_specs=(MacroTableSpec("consumer_table", ("consumer:retail_sales", "consumer:umich_sentiment", "labor:unemployment", "inflation:cpi")),),
        gap_codes=("personal_spending_missing", "consumer_credit_missing"),
        related_routes=("/macro/economy", "/macro/economy/gdp", "/macro/assets/equities"),
    ),
    "volatility": MacroModuleConfig(
        module_id="volatility",
        route_path="/macro/volatility",
        title="波动率压力",
        subtitle="VIX、3个月 VIX 与可交易波动率代理",
        question="波动率是在容忍风险，还是开始给风险资产定价压力？",
        section="volatility",
        required_concepts=("vol:vix",),
        optional_concepts=("vol:vix3m", "asset:vixy", "asset:spx"),
        chart_specs=(MacroChartSpec("volatility_context", ("vol:vix", "vol:vix3m", "asset:vixy")),),
        table_specs=(MacroTableSpec("volatility_snapshot", ("vol:vix", "vol:vix3m", "asset:vixy", "asset:spx")),),
        gap_codes=("options_iv_rv_missing",),
        related_routes=("/macro/volatility/dashboard", "/macro/volatility/vix", "/macro/assets/equities", "/macro/credit"),
    ),
    "volatility/dashboard": MacroModuleConfig(
        module_id="volatility/dashboard",
        route_path="/macro/volatility/dashboard",
        title="波动率 Dashboard",
        subtitle="风险矩阵、期限结构代理与资产确认",
        question="波动率曲线、信用和股指是否共同指向压力？",
        section="volatility",
        required_concepts=("vol:vix", "vol:vix3m"),
        optional_concepts=("asset:vixy", "credit:hy_oas", "asset:spx", "asset:qqq"),
        chart_specs=(MacroChartSpec("volatility_risk_matrix", ("vol:vix", "vol:vix3m", "credit:hy_oas", "asset:spx")),),
        table_specs=(MacroTableSpec("volatility_risk_table", ("vol:vix", "vol:vix3m", "asset:vixy", "credit:hy_oas", "asset:spx")),),
        gap_codes=("options_iv_rv_missing", "skew_surface_missing"),
        related_routes=("/macro/volatility/vix", "/macro/credit/stress", "/macro/assets/equities"),
    ),
    "volatility/vix": MacroModuleConfig(
        module_id="volatility/vix",
        route_path="/macro/volatility/vix",
        title="VIX 结构",
        subtitle="VIX、VIX3M 与短期期货代理",
        question="VIX 期限结构是在 carry，还是进入倒挂压力？",
        section="volatility",
        required_concepts=("vol:vix", "vol:vix3m"),
        optional_concepts=("asset:vixy",),
        chart_specs=(MacroChartSpec("vix_term_proxy", ("vol:vix", "vol:vix3m", "asset:vixy")),),
        table_specs=(MacroTableSpec("vix_term_proxy_table", ("vol:vix", "vol:vix3m", "asset:vixy")),),
        gap_codes=("vix_futures_curve_missing",),
        related_routes=("/macro/volatility/dashboard", "/macro/credit/stress"),
    ),
    "credit": MacroModuleConfig(
        module_id="credit",
        route_path="/macro/credit",
        title="信用压力",
        subtitle="IG/HY OAS、评级分层与信用 ETF 确认",
        question="信用利差是在确认风险偏好，还是预警去杠杆？",
        section="credit",
        required_concepts=("credit:hy_oas", "credit:ig_oas"),
        optional_concepts=("credit:bbb_oas", "credit:hy_bb_oas", "credit:hy_b_oas", "credit:hy_ccc_oas", "asset:hyg", "asset:lqd"),
        chart_specs=(MacroChartSpec("credit_spreads", ("credit:ig_oas", "credit:bbb_oas", "credit:hy_oas", "credit:hy_ccc_oas")),),
        table_specs=(
            MacroTableSpec(
                "credit_oas_ladder",
                (
                    "credit:ig_oas",
                    "credit:bbb_oas",
                    "credit:hy_oas",
                    "credit:hy_bb_oas",
                    "credit:hy_b_oas",
                    "credit:hy_ccc_oas",
                    "asset:hyg",
                    "asset:lqd",
                ),
            ),
        ),
        gap_codes=(),
        related_routes=("/macro/credit/stress", "/macro/credit/cds", "/macro/volatility/dashboard", "/macro/assets/bonds"),
    ),
    "credit/cds": MacroModuleConfig(
        module_id="credit/cds",
        route_path="/macro/credit/cds",
        title="CDS / CDX 代理",
        subtitle="公开 OAS 代理；单名 CDS/CDX 属付费数据",
        question="公开信用代理是否足以替代 CDS 压力观察？",
        section="credit",
        required_concepts=("credit:ig_oas", "credit:hy_oas"),
        optional_concepts=("credit:bbb_oas", "credit:hy_bb_oas", "asset:hyg", "asset:lqd"),
        chart_specs=(MacroChartSpec("cds_public_proxy", ("credit:ig_oas", "credit:hy_oas", "credit:bbb_oas", "asset:hyg")),),
        table_specs=(MacroTableSpec("cds_proxy_table", ("credit:ig_oas", "credit:hy_oas", "credit:bbb_oas", "credit:hy_bb_oas", "asset:hyg", "asset:lqd")),),
        gap_codes=("single_name_cds_paid_missing", "cdx_markit_paid_missing"),
        related_routes=("/macro/credit", "/macro/credit/stress", "/macro/volatility/dashboard"),
    ),
    "credit/stress": MacroModuleConfig(
        module_id="credit/stress",
        route_path="/macro/credit/stress",
        title="信用压力分解",
        subtitle="OAS 分层、融资成本与风险资产确认",
        question="压力来自高收益尾部、投资级融资成本，还是 ETF 流动性？",
        section="credit",
        required_concepts=("credit:hy_oas", "credit:ig_oas", "credit:hy_ccc_oas"),
        optional_concepts=("credit:hy_yield", "credit:ig_yield", "asset:hyg", "asset:lqd", "vol:vix"),
        chart_specs=(MacroChartSpec("credit_stress_stack", ("credit:ig_oas", "credit:hy_oas", "credit:hy_ccc_oas", "vol:vix")),),
        table_specs=(
            MacroTableSpec(
                "credit_stress_table",
                ("credit:ig_oas", "credit:hy_oas", "credit:hy_ccc_oas", "credit:ig_yield", "credit:hy_yield", "asset:hyg", "asset:lqd"),
            ),
        ),
        gap_codes=("sloos_missing", "loan_quality_missing", "dealer_inventory_missing"),
        related_routes=("/macro/credit", "/macro/credit/cds", "/macro/volatility/vix"),
    ),
}


def list_macro_module_configs() -> tuple[MacroModuleConfig, ...]:
    return tuple(_MODULE_CONFIGS[module_id] for module_id in MACRO_MODULE_IDS)


def get_macro_module_config(module_id: str) -> MacroModuleConfig:
    config = _MODULE_CONFIGS.get(module_id)
    if config is None:
        raise UnsupportedMacroModuleError(module_id)
    return config


__all__ = [
    "MACRO_MODULE_IDS",
    "MacroChartSpec",
    "MacroModuleConfig",
    "MacroTableSpec",
    "UnsupportedMacroModuleError",
    "get_macro_module_config",
    "list_macro_module_configs",
]
