import type { components } from "./openapi";

export type { components, operations, paths } from "./openapi";

export type OpenApiBootstrapData = components["schemas"]["BootstrapData"];
export type OpenApiStatusData = components["schemas"]["StatusData"];
export type OpenApiRecentData = components["schemas"]["RecentData"];
export type OpenApiSearchData = components["schemas"]["SearchData"];
export type OpenApiSearchInspectData = components["schemas"]["SearchInspectData"];
export type OpenApiTokenRadarData = components["schemas"]["TokenRadarData"];
export type OpenApiStocksRadarData = components["schemas"]["StocksRadarData"];
export type OpenApiLiveMarketData = components["schemas"]["LiveMarketData"];
export type OpenApiTargetPostsData = components["schemas"]["TargetPostsData"];
export type OpenApiTargetSocialTimelineData = components["schemas"]["TargetSocialTimelineData"];
export type OpenApiAccountAlertsData = components["schemas"]["AccountAlertsData"];
export type OpenApiNotificationSummary = components["schemas"]["NotificationSummary"];
export type OpenApiNotificationsData = components["schemas"]["NotificationsData"];
export type OpenApiNotificationReadData = components["schemas"]["NotificationReadData"];
export type OpenApiNotificationReadAllData = components["schemas"]["NotificationReadAllData"];

// frontend-contracts: these UI/domain shapes still encode frontend-specific view models
// that are richer than the current extensible OpenAPI response schemas.
export type {
  AlertRecord,
  ApiResponse,
  AssetFlowData,
  AssetFlowRow,
  BootstrapData,
  Decision,
  EntityRecord,
  EventRecord,
  FactorPoint,
  LiveMarketUpdatePayload,
  LivePayload,
  LiveMarketSnapshot,
  MacroAssetCorrelationAsset,
  MacroAssetCorrelationData,
  MacroAssetCorrelationGap,
  MacroAssetCorrelationMatrixRow,
  MacroAssetCorrelationPair,
  MacroAssetCorrelationWindow,
  MacroChainNode,
  MacroDataHealth,
  MacroIndicator,
  MacroFeatureSnapshot,
  MacroModuleChart,
  MacroModuleSnapshot,
  MacroModuleTable,
  MacroModuleTile,
  MacroModuleView,
  MacroPanel,
  MacroScenario,
  MacroScorecard,
  MacroSemanticRecord,
  MacroSeriesData,
  MacroSeriesPayload,
  MacroSeriesPoint,
  MacroTrigger,
  MacroTransmissionNode,
  MacroData,
  MacroSnapshotSummary,
  MarketCandle,
  MarketContext,
  MarketObservationSnapshot,
  NarrativeAdmission,
  NarrativeAdmissionCurrentness,
  NarrativeAdmissionCurrentnessStatus,
  NarrativeAdmissionStatus,
  NotificationItem,
  NotificationLivePayload,
  NotificationSummary,
  NotificationsData,
  RadarSortMode,
  RecentData,
  ScopeKey,
  SearchAgentBrief,
  SearchAmbiguousResult,
  SearchData,
  SearchInspectData,
  SearchItem,
  SearchTargetCandidate,
  SearchTopicResult,
  SearchTokenResult,
  ScoreBlock,
  ScoreContribution,
  SourceEventDetail,
  SourceEventsByIdsData,
  StatusData,
  WorkerStatusData,
  StockRadarRow,
  StocksRadarData,
  TimelineBucket,
  TimingBlock,
  TokenDetailMode,
  TokenCaseDossier,
  TokenCaseApiScope,
  TokenCasePostsData,
  TokenCasePostsQuery,
  TokenCaseSocialTimelineData,
  TokenCaseSocialTimelineQuery,
  TokenFactorFamily,
  TokenFactorFamilyKey,
  TokenFactorSnapshot,
  TokenFlowItem,
  TokenIntentRecord,
  TokenMarketBlock,
  TokenPostItem,
  TokenPostRange,
  TokenPostServerSort,
  TokenPostSortMode,
  TokenPostsData,
  TokenProfileBlock,
  TokenRadarRowMeta,
  TokenReference,
  TokenResolutionRecord,
  TokenSocialTimelineData,
  TokenTimelineStage,
  TokenTimelinePost,
  TradeabilityBlock,
  WatchlistHandleOverviewData,
  WatchlistHandleRowOverview,
  WatchlistHandlesOverviewData,
  WatchlistOverviewCluster,
  WatchlistHandleTimelineData,
  WatchlistTimelineItem,
  WindowKey,
} from "./frontend-contracts";
