/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Alerts */
        get: operations["account_alerts_api_account_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Quality */
        get: operations["account_quality_api_account_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrichment-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enrichment Jobs */
        get: operations["enrichment_jobs_api_enrichment_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live-market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Market */
        get: operations["live_market_api_live_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Deliveries */
        get: operations["notification_deliveries_api_notification_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Summary */
        get: operations["notification_summary_api_notification_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Notifications Read */
        post: operations["mark_all_notifications_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Inspect */
        get: operations["search_inspect_api_search_inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal-lab/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Lab Pulse */
        get: operations["signal_lab_pulse_api_signal_lab_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal-lab/pulse/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Lab Pulse By Id */
        get: operations["signal_lab_pulse_by_id_api_signal_lab_pulse__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Events */
        get: operations["social_events_api_social_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social-events/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Events By Ids */
        get: operations["social_events_by_ids_api_social_events_by_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks Radar */
        get: operations["stocks_radar_api_stocks_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Posts */
        get: operations["target_posts_api_target_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-social-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Social Timeline */
        get: operations["target_social_timeline_api_target_social_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token-case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token Case */
        get: operations["token_case_api_token_case_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token Radar */
        get: operations["token_radar_api_token_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Overview */
        get: operations["watchlist_handle_overview_api_watchlist_handle__handle__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Summary */
        get: operations["watchlist_handle_summary_api_watchlist_handle__handle__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Timeline */
        get: operations["watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handles/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handles Overview */
        get: operations["watchlist_handles_overview_api_watchlist_handles_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountAlertsData */
        AccountAlertsData: {
            /** Alert Type */
            alert_type?: string | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** AccountQualityData */
        AccountQualityData: {
            /** Accounts */
            accounts?: {
                [key: string]: unknown;
            }[];
            /** Query */
            query?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[AccountAlertsData] */
        ApiEnvelope_AccountAlertsData_: {
            data?: components["schemas"]["AccountAlertsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[AccountQualityData] */
        ApiEnvelope_AccountQualityData_: {
            data?: components["schemas"]["AccountQualityData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[BootstrapData] */
        ApiEnvelope_BootstrapData_: {
            data?: components["schemas"]["BootstrapData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[EnrichmentJobsData] */
        ApiEnvelope_EnrichmentJobsData_: {
            data?: components["schemas"]["EnrichmentJobsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[LiveMarketData] */
        ApiEnvelope_LiveMarketData_: {
            data?: components["schemas"]["LiveMarketData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[LooseData] */
        ApiEnvelope_LooseData_: {
            data?: components["schemas"]["LooseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationDeliveriesData] */
        ApiEnvelope_NotificationDeliveriesData_: {
            data?: components["schemas"]["NotificationDeliveriesData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationReadAllData] */
        ApiEnvelope_NotificationReadAllData_: {
            data?: components["schemas"]["NotificationReadAllData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationReadData] */
        ApiEnvelope_NotificationReadData_: {
            data?: components["schemas"]["NotificationReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationSummary] */
        ApiEnvelope_NotificationSummary_: {
            data?: components["schemas"]["NotificationSummary"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationsData] */
        ApiEnvelope_NotificationsData_: {
            data?: components["schemas"]["NotificationsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[RecentData] */
        ApiEnvelope_RecentData_: {
            data?: components["schemas"]["RecentData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SearchData] */
        ApiEnvelope_SearchData_: {
            data?: components["schemas"]["SearchData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SearchInspectData] */
        ApiEnvelope_SearchInspectData_: {
            data?: components["schemas"]["SearchInspectData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SignalPulseData] */
        ApiEnvelope_SignalPulseData_: {
            data?: components["schemas"]["SignalPulseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SignalPulseItem] */
        ApiEnvelope_SignalPulseItem_: {
            data?: components["schemas"]["SignalPulseItem"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SocialEventsByIdsData] */
        ApiEnvelope_SocialEventsByIdsData_: {
            data?: components["schemas"]["SocialEventsByIdsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[StatusData] */
        ApiEnvelope_StatusData_: {
            data?: components["schemas"]["StatusData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[StocksRadarData] */
        ApiEnvelope_StocksRadarData_: {
            data?: components["schemas"]["StocksRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TargetPostsData] */
        ApiEnvelope_TargetPostsData_: {
            data?: components["schemas"]["TargetPostsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TargetSocialTimelineData] */
        ApiEnvelope_TargetSocialTimelineData_: {
            data?: components["schemas"]["TargetSocialTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TokenCaseData] */
        ApiEnvelope_TokenCaseData_: {
            data?: components["schemas"]["TokenCaseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TokenRadarData] */
        ApiEnvelope_TokenRadarData_: {
            data?: components["schemas"]["TokenRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandleOverviewData] */
        ApiEnvelope_WatchlistHandleOverviewData_: {
            data?: components["schemas"]["WatchlistHandleOverviewData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandleSummaryData] */
        ApiEnvelope_WatchlistHandleSummaryData_: {
            data?: components["schemas"]["WatchlistHandleSummaryData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandleTimelineData] */
        ApiEnvelope_WatchlistHandleTimelineData_: {
            data?: components["schemas"]["WatchlistHandleTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandlesOverviewData] */
        ApiEnvelope_WatchlistHandlesOverviewData_: {
            data?: components["schemas"]["WatchlistHandlesOverviewData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** BootstrapData */
        BootstrapData: {
            /** Handles */
            handles?: string[];
            /** Replay Limit */
            replay_limit: number;
            /** Ws Token */
            ws_token: string;
        } & {
            [key: string]: unknown;
        };
        /** EnrichmentJobsData */
        EnrichmentJobsData: {
            /** Counts */
            counts?: {
                [key: string]: unknown;
            };
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveMarketData */
        LiveMarketData: {
            /** Market */
            market?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status?: string | null;
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        } & {
            [key: string]: unknown;
        };
        /** LooseData */
        LooseData: {
            [key: string]: unknown;
        };
        /** NotificationDeliveriesData */
        NotificationDeliveriesData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** NotificationReadAllData */
        NotificationReadAllData: {
            /** Updated Count */
            updated_count: number;
        } & {
            [key: string]: unknown;
        };
        /** NotificationReadData */
        NotificationReadData: {
            /** Notification Id */
            notification_id: string;
            /** Updated */
            updated: boolean;
        } & {
            [key: string]: unknown;
        };
        /** NotificationSummary */
        NotificationSummary: {
            /** Account Unread Counts */
            account_unread_counts?: {
                [key: string]: unknown;
            };
            /**
             * Critical Unread Count
             * @default 0
             */
            critical_unread_count: number;
            /**
             * High Unread Count
             * @default 0
             */
            high_unread_count: number;
            /** Highest Unread Severity */
            highest_unread_severity?: string | null;
            /** Subscriber Key */
            subscriber_key?: string | null;
            /**
             * Unread Count
             * @default 0
             */
            unread_count: number;
        } & {
            [key: string]: unknown;
        };
        /** NotificationsData */
        NotificationsData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: components["schemas"]["NotificationSummary"] | {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** RecentData */
        RecentData: {
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Scope */
            scope: string;
        } & {
            [key: string]: unknown;
        };
        /** SearchData */
        SearchData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Page */
            page: {
                [key: string]: unknown;
            };
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Target Candidates */
            target_candidates?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** SearchInspectData */
        SearchInspectData: {
            /** Ambiguous Result */
            ambiguous_result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Resolver */
            resolver?: {
                [key: string]: unknown;
            } | null;
            /** Token Result */
            token_result?: {
                [key: string]: unknown;
            } | null;
            /** Topic Result */
            topic_result?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseBullBearView */
        SignalPulseBullBearView: {
            /** Strength */
            strength: string;
            /** Supporting Event Ids */
            supporting_event_ids: string[];
            /** Thesis Zh */
            thesis_zh: string;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseData */
        SignalPulseData: {
            /** Agent Worker Running */
            agent_worker_running?: boolean | null;
            /** Has More */
            has_more?: boolean | null;
            health?: components["schemas"]["SignalPulseHealth"] | null;
            /** Items */
            items?: components["schemas"]["SignalPulseItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query?: {
                [key: string]: unknown;
            } | null;
            /** Returned Count */
            returned_count?: number | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Total Count */
            total_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseDecision */
        SignalPulseDecision: {
            /** Abstain Reason */
            abstain_reason: string | null;
            bear_view: components["schemas"]["SignalPulseBullBearView"] | null;
            bull_view: components["schemas"]["SignalPulseBullBearView"] | null;
            /** Confidence */
            confidence: number | null;
            /** Data Gap Refs */
            data_gap_refs?: string[];
            /** Evidence Event Ids */
            evidence_event_ids: string[];
            /** Evidence Event Urls */
            evidence_event_urls: {
                [key: string]: string;
            };
            /** Invalidation Conditions */
            invalidation_conditions: string[];
            /** Narrative Archetype */
            narrative_archetype: string | null;
            /** Narrative Thesis Zh */
            narrative_thesis_zh: string | null;
            playbook: components["schemas"]["SignalPulsePlaybook"] | null;
            /** Recommendation */
            recommendation: string | null;
            /** Residual Risks */
            residual_risks: string[];
            /** Risk Evidence Refs */
            risk_evidence_refs?: string[];
            /** Route */
            route: string | null;
            /** Summary Zh */
            summary_zh: string | null;
            /** Supporting Evidence Refs */
            supporting_evidence_refs?: string[];
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseHealth */
        SignalPulseHealth: {
            /** Agent Failed 4H */
            agent_failed_4h?: number | null;
            /** Agent Failure Rate 4H */
            agent_failure_rate_4h?: number | null;
            /** Agent Runs 4H */
            agent_runs_4h?: number | null;
            /** Agent Worker Running */
            agent_worker_running?: boolean | null;
            /** Blocked Low Information Count */
            blocked_low_information_count?: number | null;
            /** Candidate Count */
            candidate_count?: number | null;
            /** Claimed Jobs */
            claimed_jobs?: number | null;
            /** Dead Job Count */
            dead_job_count?: number | null;
            /** Due Jobs */
            due_jobs?: number | null;
            /** Failed Jobs 4H */
            failed_jobs_4h?: number | null;
            /** Hidden Abstain 4H */
            hidden_abstain_4h?: number | null;
            /** Hidden Hold Publish 4H */
            hidden_hold_publish_4h?: number | null;
            /** Hidden Insufficient Evidence 4H */
            hidden_insufficient_evidence_4h?: number | null;
            /** Latest Agent Run Finished At Ms */
            latest_agent_run_finished_at_ms?: number | null;
            /** Latest Packet Created At Ms */
            latest_packet_created_at_ms?: number | null;
            /** Latest Public Candidate Updated At Ms */
            latest_public_candidate_updated_at_ms?: number | null;
            /** Market Ready Rate */
            market_ready_rate?: number | null;
            /** Public Candidates 4H */
            public_candidates_4h?: number | null;
            /** Publish Status */
            publish_status?: string | null;
            /** Pulse Ready */
            pulse_ready?: boolean | null;
            /** Reasons */
            reasons?: string[];
            /** Scope */
            scope?: string | null;
            /** Since Hours */
            since_hours?: number | null;
            /** Unknown Ref Failure Rate 4H */
            unknown_ref_failure_rate_4h?: number | null;
            /** Unknown Ref Failures 4H */
            unknown_ref_failures_4h?: number | null;
            /** Unsupported Claim Failure Rate 4H */
            unsupported_claim_failure_rate_4h?: number | null;
            /** Unsupported Claim Failures 4H */
            unsupported_claim_failures_4h?: number | null;
            /** Window */
            window?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseItem */
        SignalPulseItem: {
            /** Agent Run Id */
            agent_run_id?: string | null;
            /** Candidate Id */
            candidate_id?: string | null;
            /** Candidate Score */
            candidate_score?: number | null;
            /** Candidate Type */
            candidate_type?: string | null;
            /** Claim Verification */
            claim_verification?: {
                [key: string]: unknown;
            } | null;
            /** Created At Ms */
            created_at_ms?: number | null;
            decision?: components["schemas"]["SignalPulseDecision"] | null;
            /** Decision Status */
            decision_status?: string | null;
            /** Display Status */
            display_status?: string | null;
            /** Evidence Event Ids */
            evidence_event_ids?: string[];
            /** Evidence Gate */
            evidence_gate?: {
                [key: string]: unknown;
            } | null;
            /** Evidence Packet Hash */
            evidence_packet_hash?: string | null;
            /** Evidence Status */
            evidence_status?: string | null;
            /** Fact Card */
            fact_card?: {
                [key: string]: unknown;
            } | null;
            /** Factor Snapshot */
            factor_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Gate */
            gate?: {
                [key: string]: unknown;
            } | null;
            /** Gate Reasons */
            gate_reasons?: string[];
            /** Gate Version */
            gate_version?: string | null;
            /** Last Edge Events */
            last_edge_events?: string[];
            /** Playbooks */
            playbooks?: {
                [key: string]: unknown;
            }[];
            /** Prompt Version */
            prompt_version?: string | null;
            /** Pulse Status */
            pulse_status?: string | null;
            /** Pulse Version */
            pulse_version?: string | null;
            /** Risk Reasons */
            risk_reasons?: string[];
            /** Schema Version */
            schema_version?: string | null;
            /** Scope */
            scope?: string | null;
            /** Score Band */
            score_band?: string | null;
            /** Social Phase */
            social_phase?: string | null;
            /** Source Event Ids */
            source_event_ids?: string[];
            stages?: components["schemas"]["SignalPulseStages"] | null;
            /** Subject */
            subject?: {
                [key: string]: unknown;
            } | null;
            /** Subject Key */
            subject_key?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Target Type */
            target_type?: string | null;
            /** Updated At Ms */
            updated_at_ms?: number | null;
            /** Verdict */
            verdict?: string | null;
            /** Window */
            window?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulsePlaybook */
        SignalPulsePlaybook: {
            /** Exit Triggers */
            exit_triggers: string[];
            /** Has Playbook */
            has_playbook: boolean;
            /** Monitoring Horizon */
            monitoring_horizon: string;
            /** Watch Signals */
            watch_signals: string[];
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseStagePayload */
        SignalPulseStagePayload: {
            /** Attempt Index */
            attempt_index?: number | null;
            /** Error */
            error?: string | null;
            /** Finished At Ms */
            finished_at_ms?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model?: string | null;
            /** Response */
            response?: {
                [key: string]: unknown;
            } | null;
            /** Route */
            route?: string | null;
            /** Stage */
            stage?: string | null;
            /** Started At Ms */
            started_at_ms?: number | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseStages */
        SignalPulseStages: {
            claim_verifier?: components["schemas"]["SignalPulseStagePayload"] | null;
            decision_maker?: components["schemas"]["SignalPulseStagePayload"] | null;
            deterministic_eval?: components["schemas"]["SignalPulseStagePayload"] | null;
            evidence_completeness_gate?: components["schemas"]["SignalPulseStagePayload"] | null;
            evidence_debate?: components["schemas"]["SignalPulseStagePayload"] | null;
            evidence_pack?: components["schemas"]["SignalPulseStagePayload"] | null;
            recommendation_clipper?: components["schemas"]["SignalPulseStagePayload"] | null;
            write_gate?: components["schemas"]["SignalPulseStagePayload"] | null;
        };
        /** SocialEventDetail */
        SocialEventDetail: {
            /** Action */
            action: string;
            /** Author Followers */
            author_followers?: number | null;
            /** Author Handle */
            author_handle?: string | null;
            /** Author Name */
            author_name?: string | null;
            /**
             * Author Watched
             * @default false
             */
            author_watched: boolean;
            /** Canonical Url */
            canonical_url?: string | null;
            /** Channel */
            channel: string;
            /** Event Id */
            event_id: string;
            /** Source Provider */
            source_provider: string;
            /** Text Clean */
            text_clean?: string | null;
            /** Timestamp Ms */
            timestamp_ms: number;
        } & {
            [key: string]: unknown;
        };
        /** SocialEventsByIdsData */
        SocialEventsByIdsData: {
            /** Events */
            events?: components["schemas"]["SocialEventDetail"][];
            /** Not Found */
            not_found?: string[];
        } & {
            [key: string]: unknown;
        };
        /** StatusData */
        StatusData: {
            /** Db */
            db?: {
                [key: string]: unknown;
            } | null;
            /** Handles */
            handles?: string[];
            /** Ok */
            ok: boolean;
            /** Provider States */
            provider_states?: {
                [key: string]: unknown;
            };
            /** Reasons */
            reasons?: string[];
            /** Snapshot Gate */
            snapshot_gate?: {
                [key: string]: unknown;
            };
            /** Store */
            store?: string | null;
            /** Workers */
            workers?: {
                [key: string]: components["schemas"]["WorkerStatusData"];
            };
        } & {
            [key: string]: unknown;
        };
        /** StocksRadarData */
        StocksRadarData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Projection */
            projection?: {
                [key: string]: unknown;
            } | null;
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Scope */
            scope?: string | null;
            /** Window */
            window?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TargetPostsData */
        TargetPostsData: {
            /** Has More */
            has_more?: boolean | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Returned Count */
            returned_count?: number | null;
            /** Score Window */
            score_window?: {
                [key: string]: unknown;
            } | null;
            /** Total Count */
            total_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TargetSocialTimelineData */
        TargetSocialTimelineData: {
            /** Authors */
            authors?: {
                [key: string]: unknown;
            }[];
            /** Buckets */
            buckets?: {
                [key: string]: unknown;
            }[];
            /** Cascade */
            cascade?: {
                [key: string]: unknown;
            } | null;
            /** Has More */
            has_more?: boolean | null;
            /** Market Candles */
            market_candles?: {
                [key: string]: unknown;
            } | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Posts */
            posts?: {
                [key: string]: unknown;
            }[];
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Returned Count */
            returned_count?: number | null;
            /** Stages */
            stages?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** TokenCaseData */
        TokenCaseData: {
            /** Discussion Digest */
            discussion_digest: {
                [key: string]: unknown;
            };
            /** Market Live */
            market_live: {
                [key: string]: unknown;
            };
            /** Narrative Clusters */
            narrative_clusters?: {
                [key: string]: unknown;
            }[];
            /** Posts */
            posts: {
                [key: string]: unknown;
            };
            /** Profile */
            profile?: {
                [key: string]: unknown;
            } | null;
            /** Pulse Overlay */
            pulse_overlay?: {
                [key: string]: unknown;
            } | null;
            /** Target */
            target: {
                [key: string]: unknown;
            };
            /** Timeline */
            timeline: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** TokenRadarData */
        TokenRadarData: {
            /** Attention */
            attention?: {
                [key: string]: unknown;
            }[];
            /** Projection */
            projection?: {
                [key: string]: unknown;
            };
            /** Scope */
            scope: string;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            }[];
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistHandleOverviewData */
        WatchlistHandleOverviewData: {
            /** Candidate Mention Clusters */
            candidate_mention_clusters?: components["schemas"]["WatchlistOverviewCluster"][];
            /**
             * Clusters Truncated
             * @default false
             */
            clusters_truncated: boolean;
            metrics: components["schemas"]["WatchlistOverviewMetrics"];
            /** Narrative Clusters */
            narrative_clusters?: components["schemas"]["WatchlistOverviewCluster"][];
            query: components["schemas"]["WatchlistOverviewQuery"];
            /** Resolved Token Clusters */
            resolved_token_clusters?: components["schemas"]["WatchlistOverviewCluster"][];
            /** Risk Notes */
            risk_notes?: string[];
        } & {
            [key: string]: unknown;
        };
        /** WatchlistHandleRowOverview */
        WatchlistHandleRowOverview: {
            /** Handle */
            handle: string;
            /** Last Source Event At Ms */
            last_source_event_at_ms?: number | null;
            /**
             * Recent Signal Event Count
             * @default 0
             */
            recent_signal_event_count: number;
            /**
             * Recent Source Event Count
             * @default 0
             */
            recent_source_event_count: number;
            /**
             * Summary Is Stale
             * @default false
             */
            summary_is_stale: boolean;
            /**
             * Summary Status
             * @enum {string}
             */
            summary_status: "ready" | "not_ready";
            /**
             * Total Signal Event Count
             * @default 0
             */
            total_signal_event_count: number;
        } & {
            [key: string]: unknown;
        };
        /** WatchlistHandleSummaryData */
        WatchlistHandleSummaryData: {
            /** Generated At Ms */
            generated_at_ms?: number | null;
            /** Handle */
            handle: string;
            /**
             * Input Event Count
             * @default 0
             */
            input_event_count: number;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Model */
            model?: string | null;
            /**
             * Pending Recompute
             * @default false
             */
            pending_recompute: boolean;
            /**
             * Signal Count
             * @default 0
             */
            signal_count: number;
            /**
             * Signal Count At Generation
             * @default 0
             */
            signal_count_at_generation: number;
            /** Staleness Ms */
            staleness_ms?: number | null;
            /** Status */
            status: string;
            /**
             * Summary Zh
             * @default
             */
            summary_zh: string;
            /** Topics */
            topics?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** WatchlistHandleTimelineData */
        WatchlistHandleTimelineData: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** WatchlistHandlesOverviewData */
        WatchlistHandlesOverviewData: {
            /** Items */
            items?: components["schemas"]["WatchlistHandleRowOverview"][];
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** WatchlistOverviewCluster */
        WatchlistOverviewCluster: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resolved_token" | "candidate_mention" | "narrative";
            /** Label */
            label: string;
            /** Query */
            query: string;
            /** Source */
            source: string;
            /** Symbol */
            symbol?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Target Type */
            target_type?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** WatchlistOverviewMetrics */
        WatchlistOverviewMetrics: {
            /**
             * Candidate Mention Count
             * @default 0
             */
            candidate_mention_count: number;
            /** Last Source Event At Ms */
            last_source_event_at_ms?: number | null;
            /**
             * Narrative Count
             * @default 0
             */
            narrative_count: number;
            /**
             * Resolved Token Count
             * @default 0
             */
            resolved_token_count: number;
            /**
             * Signal Event Count
             * @default 0
             */
            signal_event_count: number;
            /**
             * Source Event Count
             * @default 0
             */
            source_event_count: number;
        } & {
            [key: string]: unknown;
        };
        /** WatchlistOverviewQuery */
        WatchlistOverviewQuery: {
            /** Handle */
            handle: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "signal" | "all";
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** WorkerStatusData */
        WorkerStatusData: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /** Iteration Duration P99 Ms */
            iteration_duration_p99_ms?: number | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Finished At Ms */
            last_finished_at_ms?: number | null;
            /** Last Result */
            last_result?: {
                [key: string]: unknown;
            } | null;
            /** Last Started At Ms */
            last_started_at_ms?: number | null;
            /** Pool Wait Ms P99 */
            pool_wait_ms_p99?: number | null;
            /** Queue Depth */
            queue_depth?: number | null;
            /** Running */
            running: boolean;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_alerts_api_account_alerts_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
                alert_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_AccountAlertsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_quality_api_account_quality_get: {
        parameters: {
            query?: {
                handles?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_AccountQualityData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_BootstrapData_"];
                };
            };
        };
    };
    enrichment_jobs_api_enrichment_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_EnrichmentJobsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_market_api_live_market_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LiveMarketData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_deliveries_api_notification_deliveries_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationDeliveriesData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_summary_api_notification_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationSummary_"];
                };
            };
        };
    };
    notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                unread_only?: boolean;
                rule_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_notifications_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadAllData_"];
                };
            };
        };
    };
    mark_notification_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_api_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                handles?: string;
                ca?: string;
                chain?: string;
                symbol?: string;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_RecentData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_inspect_api_search_inspect_get: {
        parameters: {
            query?: {
                q?: string;
                window?: string;
                scope?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchInspectData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_lab_pulse_api_signal_lab_pulse_get: {
        parameters: {
            query?: {
                window?: string;
                scope?: string;
                status?: string;
                handle?: string;
                q?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalPulseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_lab_pulse_by_id_api_signal_lab_pulse__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalPulseItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_events_api_social_events_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
                event_types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_events_by_ids_api_social_events_by_ids_get: {
        parameters: {
            query?: {
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SocialEventsByIdsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StatusData_"];
                };
            };
        };
    };
    stocks_radar_api_stocks_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StocksRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_posts_api_target_posts_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                range?: string;
                sort?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetPostsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_social_timeline_api_target_social_timeline_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                scope?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetSocialTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_case_api_token_case_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                scope?: string;
                posts_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TokenCaseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_radar_api_token_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TokenRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_overview_api_watchlist_handle__handle__overview_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleOverviewData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_summary_api_watchlist_handle__handle__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleSummaryData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get: {
        parameters: {
            query?: {
                scope?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handles_overview_api_watchlist_handles_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandlesOverviewData_"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusData"];
                };
            };
        };
    };
}
