/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Alerts */
        get: operations["account_alerts_api_account_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Quality */
        get: operations["account_quality_api_account_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention-seeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention Seeds */
        get: operations["attention_seeds_api_attention_seeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrichment-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enrichment Jobs */
        get: operations["enrichment_jobs_api_enrichment_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Credits */
        get: operations["harness_credits_api_harness_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Health */
        get: operations["harness_health_api_harness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Outcomes */
        get: operations["harness_outcomes_api_harness_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-score-buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Score Buckets */
        get: operations["harness_score_buckets_api_harness_score_buckets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Snapshots */
        get: operations["harness_snapshots_api_harness_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness-weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harness Weights */
        get: operations["harness_weights_api_harness_weights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live-market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Market */
        get: operations["live_market_api_live_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Deliveries */
        get: operations["notification_deliveries_api_notification_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Summary */
        get: operations["notification_summary_api_notification_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Notifications Read */
        post: operations["mark_all_notifications_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Inspect */
        get: operations["search_inspect_api_search_inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal-lab/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Lab Pulse */
        get: operations["signal_lab_pulse_api_signal_lab_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal-lab/pulse/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Lab Pulse By Id */
        get: operations["signal_lab_pulse_by_id_api_signal_lab_pulse__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Events */
        get: operations["social_events_api_social_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social-events/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Events By Ids */
        get: operations["social_events_by_ids_api_social_events_by_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks Radar */
        get: operations["stocks_radar_api_stocks_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Posts */
        get: operations["target_posts_api_target_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-social-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Social Timeline */
        get: operations["target_social_timeline_api_target_social_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token Radar */
        get: operations["token_radar_api_token_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Summary */
        get: operations["watchlist_handle_summary_api_watchlist_handle__handle__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Timeline */
        get: operations["watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountAlertsData */
        AccountAlertsData: {
            /** Alert Type */
            alert_type?: string | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** AccountQualityData */
        AccountQualityData: {
            /** Accounts */
            accounts?: {
                [key: string]: unknown;
            }[];
            /** Query */
            query?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[AccountAlertsData] */
        ApiEnvelope_AccountAlertsData_: {
            data?: components["schemas"]["AccountAlertsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[AccountQualityData] */
        ApiEnvelope_AccountQualityData_: {
            data?: components["schemas"]["AccountQualityData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[BootstrapData] */
        ApiEnvelope_BootstrapData_: {
            data?: components["schemas"]["BootstrapData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[EnrichmentJobsData] */
        ApiEnvelope_EnrichmentJobsData_: {
            data?: components["schemas"]["EnrichmentJobsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[LiveMarketData] */
        ApiEnvelope_LiveMarketData_: {
            data?: components["schemas"]["LiveMarketData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[LooseData] */
        ApiEnvelope_LooseData_: {
            data?: components["schemas"]["LooseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationDeliveriesData] */
        ApiEnvelope_NotificationDeliveriesData_: {
            data?: components["schemas"]["NotificationDeliveriesData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationReadAllData] */
        ApiEnvelope_NotificationReadAllData_: {
            data?: components["schemas"]["NotificationReadAllData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationReadData] */
        ApiEnvelope_NotificationReadData_: {
            data?: components["schemas"]["NotificationReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationSummary] */
        ApiEnvelope_NotificationSummary_: {
            data?: components["schemas"]["NotificationSummary"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[NotificationsData] */
        ApiEnvelope_NotificationsData_: {
            data?: components["schemas"]["NotificationsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[RecentData] */
        ApiEnvelope_RecentData_: {
            data?: components["schemas"]["RecentData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SearchData] */
        ApiEnvelope_SearchData_: {
            data?: components["schemas"]["SearchData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SearchInspectData] */
        ApiEnvelope_SearchInspectData_: {
            data?: components["schemas"]["SearchInspectData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SignalPulseData] */
        ApiEnvelope_SignalPulseData_: {
            data?: components["schemas"]["SignalPulseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SignalPulseItem] */
        ApiEnvelope_SignalPulseItem_: {
            data?: components["schemas"]["SignalPulseItem"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[SocialEventsByIdsData] */
        ApiEnvelope_SocialEventsByIdsData_: {
            data?: components["schemas"]["SocialEventsByIdsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[StatusData] */
        ApiEnvelope_StatusData_: {
            data?: components["schemas"]["StatusData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[StocksRadarData] */
        ApiEnvelope_StocksRadarData_: {
            data?: components["schemas"]["StocksRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TargetPostsData] */
        ApiEnvelope_TargetPostsData_: {
            data?: components["schemas"]["TargetPostsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TargetSocialTimelineData] */
        ApiEnvelope_TargetSocialTimelineData_: {
            data?: components["schemas"]["TargetSocialTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[TokenRadarData] */
        ApiEnvelope_TokenRadarData_: {
            data?: components["schemas"]["TokenRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandleSummaryData] */
        ApiEnvelope_WatchlistHandleSummaryData_: {
            data?: components["schemas"]["WatchlistHandleSummaryData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ApiEnvelope[WatchlistHandleTimelineData] */
        ApiEnvelope_WatchlistHandleTimelineData_: {
            data?: components["schemas"]["WatchlistHandleTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /** BootstrapData */
        BootstrapData: {
            /** Handles */
            handles?: string[];
            /** Replay Limit */
            replay_limit: number;
            /** Ws Token */
            ws_token: string;
        } & {
            [key: string]: unknown;
        };
        /** EnrichmentJobsData */
        EnrichmentJobsData: {
            /** Counts */
            counts?: {
                [key: string]: unknown;
            };
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveMarketData */
        LiveMarketData: {
            /** Market */
            market?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status?: string | null;
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        } & {
            [key: string]: unknown;
        };
        /** LooseData */
        LooseData: {
            [key: string]: unknown;
        };
        /** NotificationDeliveriesData */
        NotificationDeliveriesData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** NotificationReadAllData */
        NotificationReadAllData: {
            /** Updated Count */
            updated_count: number;
        } & {
            [key: string]: unknown;
        };
        /** NotificationReadData */
        NotificationReadData: {
            /** Notification Id */
            notification_id: string;
            /** Updated */
            updated: boolean;
        } & {
            [key: string]: unknown;
        };
        /** NotificationSummary */
        NotificationSummary: {
            /** Account Unread Counts */
            account_unread_counts?: {
                [key: string]: unknown;
            };
            /**
             * Critical Unread Count
             * @default 0
             */
            critical_unread_count: number;
            /**
             * High Unread Count
             * @default 0
             */
            high_unread_count: number;
            /** Highest Unread Severity */
            highest_unread_severity?: string | null;
            /** Subscriber Key */
            subscriber_key?: string | null;
            /**
             * Unread Count
             * @default 0
             */
            unread_count: number;
        } & {
            [key: string]: unknown;
        };
        /** NotificationsData */
        NotificationsData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: components["schemas"]["NotificationSummary"] | {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** RecentData */
        RecentData: {
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Scope */
            scope: string;
        } & {
            [key: string]: unknown;
        };
        /** SearchData */
        SearchData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Page */
            page: {
                [key: string]: unknown;
            };
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Target Candidates */
            target_candidates?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** SearchInspectData */
        SearchInspectData: {
            /** Error */
            error?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Resolver */
            resolver?: {
                [key: string]: unknown;
            } | null;
            /** Token Result */
            token_result?: {
                [key: string]: unknown;
            } | null;
            /** Topic Result */
            topic_result?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseData */
        SignalPulseData: {
            /** Agent Worker Running */
            agent_worker_running?: boolean | null;
            /** Has More */
            has_more?: boolean | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Total Count */
            total_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseItem */
        SignalPulseItem: {
            /** Candidate Id */
            candidate_id?: string | null;
            /** Fact Card */
            fact_card?: {
                [key: string]: unknown;
            } | null;
            /** Recommendation */
            recommendation?: {
                [key: string]: unknown;
            } | null;
            stages?: components["schemas"]["SignalPulseStages"] | null;
            /** Status */
            status?: string | null;
            /** Target */
            target?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseStagePayload */
        SignalPulseStagePayload: {
            /** Attempt Index */
            attempt_index?: number | null;
            /** Error */
            error?: string | null;
            /** Finished At Ms */
            finished_at_ms?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model?: string | null;
            /** Response */
            response?: {
                [key: string]: unknown;
            } | null;
            /** Route */
            route?: string | null;
            /** Stage */
            stage?: string | null;
            /** Started At Ms */
            started_at_ms?: number | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SignalPulseStages */
        SignalPulseStages: {
            analyst?: components["schemas"]["SignalPulseStagePayload"] | null;
            critic?: components["schemas"]["SignalPulseStagePayload"] | null;
            judge?: components["schemas"]["SignalPulseStagePayload"] | null;
            research_only_gate?: components["schemas"]["SignalPulseStagePayload"] | null;
        } & {
            [key: string]: unknown;
        };
        /** SocialEventDetail */
        SocialEventDetail: {
            /** Action */
            action: string;
            /** Author Followers */
            author_followers?: number | null;
            /** Author Handle */
            author_handle?: string | null;
            /** Author Name */
            author_name?: string | null;
            /**
             * Author Watched
             * @default false
             */
            author_watched: boolean;
            /** Canonical Url */
            canonical_url?: string | null;
            /** Channel */
            channel: string;
            /** Event Id */
            event_id: string;
            /** Source Provider */
            source_provider: string;
            /** Text Clean */
            text_clean?: string | null;
            /** Timestamp Ms */
            timestamp_ms: number;
        } & {
            [key: string]: unknown;
        };
        /** SocialEventsByIdsData */
        SocialEventsByIdsData: {
            /** Events */
            events?: components["schemas"]["SocialEventDetail"][];
            /** Not Found */
            not_found?: string[];
        } & {
            [key: string]: unknown;
        };
        /** StatusData */
        StatusData: {
            /** Anchor Price */
            anchor_price?: {
                [key: string]: unknown;
            } | null;
            /** Collector */
            collector?: {
                [key: string]: unknown;
            } | null;
            /** Enrichment */
            enrichment?: {
                [key: string]: unknown;
            } | null;
            /** Handles */
            handles?: string[];
            /** Live Price Gateway */
            live_price_gateway?: {
                [key: string]: unknown;
            } | null;
            /** Notifications */
            notifications?: {
                [key: string]: unknown;
            } | null;
            /** Ok */
            ok: boolean;
            /** Reasons */
            reasons?: string[];
            /** Store */
            store?: string | null;
            /** Token Radar Projection */
            token_radar_projection?: {
                [key: string]: unknown;
            } | null;
            /** Watchlist Handle Summary */
            watchlist_handle_summary?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** StocksRadarData */
        StocksRadarData: {
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Projection */
            projection?: {
                [key: string]: unknown;
            } | null;
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Scope */
            scope?: string | null;
            /** Window */
            window?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TargetPostsData */
        TargetPostsData: {
            /** Has More */
            has_more?: boolean | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Returned Count */
            returned_count?: number | null;
            /** Score Window */
            score_window?: {
                [key: string]: unknown;
            } | null;
            /** Total Count */
            total_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TargetSocialTimelineData */
        TargetSocialTimelineData: {
            /** Authors */
            authors?: {
                [key: string]: unknown;
            }[];
            /** Buckets */
            buckets?: {
                [key: string]: unknown;
            }[];
            /** Cascade */
            cascade?: {
                [key: string]: unknown;
            } | null;
            /** Has More */
            has_more?: boolean | null;
            /** Market Overlay */
            market_overlay?: {
                [key: string]: unknown;
            } | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Posts */
            posts?: {
                [key: string]: unknown;
            }[];
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Returned Count */
            returned_count?: number | null;
            /** Stages */
            stages?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** TokenRadarData */
        TokenRadarData: {
            /** Attention */
            attention?: {
                [key: string]: unknown;
            }[];
            /** Projection */
            projection?: {
                [key: string]: unknown;
            };
            /** Scope */
            scope: string;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            }[];
            /** Window */
            window: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistHandleSummaryData */
        WatchlistHandleSummaryData: {
            /** Generated At Ms */
            generated_at_ms?: number | null;
            /** Handle */
            handle: string;
            /**
             * Input Event Count
             * @default 0
             */
            input_event_count: number;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Model */
            model?: string | null;
            /**
             * Pending Recompute
             * @default false
             */
            pending_recompute: boolean;
            /**
             * Signal Count
             * @default 0
             */
            signal_count: number;
            /**
             * Signal Count At Generation
             * @default 0
             */
            signal_count_at_generation: number;
            /** Staleness Ms */
            staleness_ms?: number | null;
            /** Status */
            status: string;
            /**
             * Summary Zh
             * @default
             */
            summary_zh: string;
            /** Topics */
            topics?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** WatchlistHandleTimelineData */
        WatchlistHandleTimelineData: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_alerts_api_account_alerts_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
                alert_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_AccountAlertsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_quality_api_account_quality_get: {
        parameters: {
            query?: {
                handles?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_AccountQualityData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attention_seeds_api_attention_seeds_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_BootstrapData_"];
                };
            };
        };
    };
    enrichment_jobs_api_enrichment_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_EnrichmentJobsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harness_credits_api_harness_credits_get: {
        parameters: {
            query?: {
                window?: string;
                horizon?: string;
                limit?: number;
                asset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harness_health_api_harness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
        };
    };
    harness_outcomes_api_harness_outcomes_get: {
        parameters: {
            query?: {
                window?: string;
                horizon?: string;
                limit?: number;
                asset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harness_score_buckets_api_harness_score_buckets_get: {
        parameters: {
            query?: {
                horizon?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harness_snapshots_api_harness_snapshots_get: {
        parameters: {
            query?: {
                window?: string;
                horizon?: string;
                limit?: number;
                asset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harness_weights_api_harness_weights_get: {
        parameters: {
            query?: {
                horizon?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_market_api_live_market_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LiveMarketData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_deliveries_api_notification_deliveries_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationDeliveriesData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_summary_api_notification_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationSummary_"];
                };
            };
        };
    };
    notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                unread_only?: boolean;
                rule_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_notifications_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadAllData_"];
                };
            };
        };
    };
    mark_notification_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_api_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                handles?: string;
                ca?: string;
                chain?: string;
                symbol?: string;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_RecentData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_inspect_api_search_inspect_get: {
        parameters: {
            query?: {
                q?: string;
                window?: string;
                scope?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchInspectData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_lab_pulse_api_signal_lab_pulse_get: {
        parameters: {
            query?: {
                window?: string;
                scope?: string;
                status?: string;
                handle?: string;
                q?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalPulseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_lab_pulse_by_id_api_signal_lab_pulse__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalPulseItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_events_api_social_events_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
                event_types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LooseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_events_by_ids_api_social_events_by_ids_get: {
        parameters: {
            query?: {
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SocialEventsByIdsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StatusData_"];
                };
            };
        };
    };
    stocks_radar_api_stocks_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StocksRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_posts_api_target_posts_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                range?: string;
                sort?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetPostsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_social_timeline_api_target_social_timeline_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                scope?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetSocialTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_radar_api_token_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TokenRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_summary_api_watchlist_handle__handle__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleSummaryData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get: {
        parameters: {
            query?: {
                scope?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusData"];
                };
            };
        };
    };
}
