from __future__ import annotations

MACRO_EVIDENCE_PROJECTION_VERSION = "macro_evidence_v1"
MACRO_EVIDENCE_HISTORY_LOOKBACK_DAYS = 1095
MACRO_EVIDENCE_HISTORY_LIMIT_PER_SERIES = 800
MACRO_MIN_CHART_POINTS = 2

MACRO_PROVIDER_SERIES_TO_CONCEPT = {
    "fred:WALCL": "liquidity:fed_assets",
    "fred:WRBWFRBL": "liquidity:reserve_balances",
    "fred:RRPONTSYD": "liquidity:on_rrp",
    "nyfed:RRP": "liquidity:nyfed_rrp",
    "nyfed:SRF": "liquidity:srf",
    "nyfed:SOFR": "liquidity:sofr",
    "nyfed:BGCR": "liquidity:bgcr",
    "nyfed:TGCR": "liquidity:tgcr",
    "nyfed:SOFR_VOLUME": "liquidity:sofr_volume",
    "nyfed:BGCR_VOLUME": "liquidity:bgcr_volume",
    "nyfed:TGCR_VOLUME": "liquidity:tgcr_volume",
    "treasury_fiscal:operating_cash_balance": "liquidity:tga",
    "fred:DFF": "fed:dff",
    "fred:DGS1MO": "rates:dgs1mo",
    "fred:DGS3MO": "rates:dgs3mo",
    "fred:DGS6MO": "rates:dgs6mo",
    "fred:DGS1": "rates:dgs1",
    "fred:DGS2": "rates:dgs2",
    "fred:DGS3": "rates:dgs3",
    "fred:DGS5": "rates:dgs5",
    "fred:DGS7": "rates:dgs7",
    "fred:DGS10": "rates:dgs10",
    "fred:DGS20": "rates:dgs20",
    "fred:DGS30": "rates:dgs30",
    "fred:T10Y2Y": "rates:10y2y",
    "fred:T10Y3M": "rates:10y3m",
    "fred:DFII5": "rates:real_5y",
    "fred:DFII10": "rates:real_10y",
    "fred:DFII30": "rates:real_30y",
    "fred:T5YIE": "inflation:5y_breakeven",
    "fred:T10YIE": "inflation:10y_breakeven",
    "fred:T5YIFR": "inflation:5y5y_forward",
    "fred:MICH": "inflation:mich_1y_expectation",
    "fred:DFEDTARU": "fed:target_upper",
    "fred:DFEDTARL": "fed:target_lower",
    "fred:FEDFUNDS": "fed:fedfunds",
    "fred:EFFR": "fed:effr",
    "nyfed:EFFR": "fed:effr",
    "nyfed:OBFR": "fed:obfr",
    "nyfed:EFFR_VOLUME": "fed:effr_volume",
    "nyfed:OBFR_VOLUME": "fed:obfr_volume",
    "fred:IORB": "fed:iorb",
    "fred:SOFR30DAYAVG": "fed:sofr_30d",
    "fred:GDP": "economy:gdp_nominal",
    "fred:GDPC1": "economy:gdp_real",
    "fred:GDPNOW": "economy:gdp_nowcast",
    "fred:GDPDEF": "inflation:gdp_deflator",
    "fred:UNRATE": "labor:unemployment",
    "fred:PAYEMS": "labor:payrolls",
    "fred:CIVPART": "labor:participation",
    "fred:ICSA": "labor:initial_claims",
    "fred:JTSJOL": "labor:job_openings",
    "fred:CES0500000003": "labor:avg_hourly_earnings",
    "fred:CPIAUCSL": "inflation:cpi",
    "fred:CPILFESL": "inflation:core_cpi",
    "fred:PPIACO": "inflation:ppi",
    "fred:PCEPI": "inflation:pce",
    "fred:PCEPILFE": "inflation:core_pce",
    "fred:PCE": "consumer:pce_nominal",
    "fred:PCEC96": "consumer:pce_real",
    "fred:RSAFS": "consumer:retail_sales",
    "fred:INDPRO": "economy:industrial_production",
    "fred:HOUST": "economy:housing_starts",
    "fred:UMCSENT": "consumer:umich_sentiment",
    "fred:PSAVERT": "consumer:saving_rate",
    "fred:BAMLC0A0CM": "credit:ig_oas",
    "fred:BAMLC0A1CAAA": "credit:aaa_oas",
    "fred:BAMLC0A2CAA": "credit:aa_oas",
    "fred:BAMLC0A3CA": "credit:a_oas",
    "fred:BAMLC0A4CBBB": "credit:bbb_oas",
    "fred:BAMLH0A0HYM2": "credit:hy_oas",
    "fred:BAMLH0A1HYBB": "credit:hy_bb_oas",
    "fred:BAMLH0A2HYB": "credit:hy_b_oas",
    "fred:BAMLH0A3HYC": "credit:hy_ccc_oas",
    "fred:BAMLC0A0CMEY": "credit:ig_yield",
    "fred:BAMLH0A0HYM2EY": "credit:hy_yield",
    "fred:STLFSI4": "credit:stl_stress",
    "fred:NFCI": "credit:nfci",
    "fred:ANFCI": "credit:anfci",
    "fred:DRTSCILM": "credit:sloos_ci_large_tightening",
    "fred:DRTSCIS": "credit:sloos_ci_small_tightening",
    "fred:DRSDCILM": "credit:sloos_ci_large_demand",
    "fred:DRSDCIS": "credit:sloos_ci_small_demand",
    "fred:DRBLACBS": "credit:business_delinquency",
    "fred:DRCLACBS": "credit:consumer_delinquency",
    "fred:CORBLACBS": "credit:business_charge_off",
    "fred:CORCACBS": "credit:consumer_charge_off",
    "fred:VIXCLS": "vol:vix",
    "fred:VXVCLS": "vol:vix3m",
    "cboe:VIX1D": "vol:vix1d",
    "cboe:VIX9D": "vol:vix9d",
    "cboe:VVIX": "vol:vvix",
    "cboe:SKEW": "vol:skew",
    "fred:VXNCLS": "vol:vxn",
    "fred:RVXCLS": "vol:rvx",
    "fred:GVZCLS": "vol:gvz",
    "fred:OVXCLS": "vol:ovx",
    "fred:EVZCLS": "vol:evz",
    "fred:SP500": "asset:spx",
    "fred:NASDAQCOM": "asset:nasdaq",
    "fred:DCOILWTICO": "commodity:wti",
    "fred:DCOILBRENTEU": "commodity:brent",
    "fred:DHHNGSP": "commodity:natgas",
    "fred:DTWEXBGS": "fx:broad_dollar",
    "fred:DEXUSEU": "fx:fred_eurusd",
    "fred:DEXJPUS": "fx:fred_usdjpy",
    "fred:DEXCHUS": "fx:fred_usdcny",
    "fred:DEXUSUK": "fx:fred_gbpusd",
    "yahoo:^GSPC": "asset:gspc",
    "yahoo:^NDX": "asset:ndx",
    "yahoo:^DJI": "asset:dji",
    "yahoo:^RUT": "asset:rut",
    "yahoo:SPY": "asset:spy",
    "yahoo:QQQ": "asset:qqq",
    "yahoo:DIA": "asset:dia",
    "yahoo:IWM": "asset:iwm",
    "yahoo:EFA": "asset:efa",
    "yahoo:EEM": "asset:eem",
    "yahoo:SHY": "asset:shy",
    "yahoo:IEF": "asset:ief",
    "yahoo:TIP": "asset:tip",
    "yahoo:BND": "asset:bnd",
    "yahoo:TLT": "asset:tlt",
    "yahoo:HYG": "asset:hyg",
    "yahoo:JNK": "asset:jnk",
    "yahoo:LQD": "asset:lqd",
    "yahoo:GLD": "asset:gld",
    "yahoo:SLV": "asset:slv",
    "yahoo:USO": "asset:uso",
    "yahoo:^MOVE": "vol:move",
    "yahoo:VIXY": "asset:vixy",
    "yahoo:VIXM": "asset:vixm",
    "yahoo:GC=F": "commodity:gold_futures",
    "yahoo:SI=F": "commodity:silver_futures",
    "yahoo:CL=F": "commodity:wti_futures",
    "yahoo:NG=F": "commodity:natgas_futures",
    "yahoo:HG=F": "commodity:copper_futures",
    "yahoo:UNG": "asset:ung",
    "yahoo:CPER": "asset:cper",
    "yahoo:SMH": "asset:smh",
    "yahoo:SOXX": "asset:soxx",
    "yahoo:UUP": "asset:uup",
    "yahoo:FXE": "asset:fxe",
    "yahoo:FXY": "asset:fxy",
    "yahoo:DX-Y.NYB": "fx:dxy",
    "yahoo:EURUSD=X": "fx:eurusd",
    "yahoo:GBPUSD=X": "fx:gbpusd",
    "yahoo:USDJPY=X": "fx:usdjpy",
    "yahoo:USDCNY=X": "fx:usdcny",
    "yahoo:USDKRW=X": "fx:usdkrw",
    "yahoo:BTC-USD": "crypto:btc",
    "yahoo:ETH-USD": "crypto:eth",
    "okx:BTC-USDT-SWAP:open_interest_usd": "crypto_derivatives:okx_btc_oi_usd",
    "okx:BTC-USDT-SWAP:funding_rate": "crypto_derivatives:okx_btc_funding",
    "okx:BTC-USDT-SWAP:basis_pct": "crypto_derivatives:okx_btc_basis",
    "okx:ETH-USDT-SWAP:open_interest_usd": "crypto_derivatives:okx_eth_oi_usd",
    "okx:ETH-USDT-SWAP:funding_rate": "crypto_derivatives:okx_eth_funding",
    "okx:ETH-USDT-SWAP:basis_pct": "crypto_derivatives:okx_eth_basis",
    "deribit:BTC-PERPETUAL:open_interest_usd": "crypto_derivatives:deribit_btc_oi_usd",
    "deribit:BTC-PERPETUAL:funding_8h": "crypto_derivatives:deribit_btc_funding_8h",
    "deribit:BTC-PERPETUAL:basis_pct": "crypto_derivatives:deribit_btc_basis",
    "deribit:BTC:volatility_index": "crypto_derivatives:deribit_btc_vol_index",
    "deribit:ETH-PERPETUAL:open_interest_usd": "crypto_derivatives:deribit_eth_oi_usd",
    "deribit:ETH-PERPETUAL:funding_8h": "crypto_derivatives:deribit_eth_funding_8h",
    "deribit:ETH-PERPETUAL:basis_pct": "crypto_derivatives:deribit_eth_basis",
    "deribit:ETH:volatility_index": "crypto_derivatives:deribit_eth_vol_index",
    "cftc:financial_futures:sp500_net_noncommercial": "positioning:sp500_net_noncommercial",
}

MACRO_EVENT_PROVIDER_SERIES_TO_CONCEPT = {
    "official_calendar:fomc_decision_next": "event:fomc_decision_next",
    "official_calendar:bea_gdp_next": "event:bea_gdp_next",
    "official_calendar:bea_pce_next": "event:bea_pce_next",
    "official_calendar:bls_cpi_next": "event:bls_cpi_next",
    "official_calendar:bls_employment_next": "event:bls_employment_next",
    "official_calendar:bls_ppi_next": "event:bls_ppi_next",
    "official_fed_text:fomc_statement_latest": "event:fed_fomc_statement",
    "official_fed_text:fomc_minutes_latest": "event:fed_fomc_minutes",
    "official_fed_text:monetary_policy_press_release_latest": "event:fed_monetary_policy_press_release",
    "official_fed_text:speech_latest": "event:fed_speech",
    "treasury_auction:2y_next_auction_days": "event:treasury_auction_2y_next",
    "treasury_auction:10y_next_auction_days": "event:treasury_auction_10y_next",
    "treasury_auction:30y_next_auction_days": "event:treasury_auction_30y_next",
    "treasury_auction:2y_high_yield": "event:treasury_auction_2y_high_yield",
    "treasury_auction:2y_bid_to_cover": "event:treasury_auction_2y_bid_to_cover",
    "treasury_auction:2y_indirect_bidder_pct": "event:treasury_auction_2y_indirect_bidder_pct",
    "treasury_auction:10y_high_yield": "event:treasury_auction_10y_high_yield",
    "treasury_auction:10y_bid_to_cover": "event:treasury_auction_10y_bid_to_cover",
    "treasury_auction:10y_indirect_bidder_pct": "event:treasury_auction_10y_indirect_bidder_pct",
    "treasury_auction:30y_high_yield": "event:treasury_auction_30y_high_yield",
    "treasury_auction:30y_bid_to_cover": "event:treasury_auction_30y_bid_to_cover",
    "treasury_auction:30y_indirect_bidder_pct": "event:treasury_auction_30y_indirect_bidder_pct",
}

MACRO_IMPORTABLE_PROVIDER_SERIES_TO_CONCEPT = {
    **MACRO_PROVIDER_SERIES_TO_CONCEPT,
    **MACRO_EVENT_PROVIDER_SERIES_TO_CONCEPT,
}

MACRO_PROVIDER_SERIES_SOURCE_PRIORITY = {
    **{series_key: 100 for series_key in MACRO_PROVIDER_SERIES_TO_CONCEPT},
    **{series_key: 80 for series_key in MACRO_EVENT_PROVIDER_SERIES_TO_CONCEPT},
    "nyfed:EFFR": 110,
}

MACRO_EVENT_CONCEPTS = tuple(dict.fromkeys(MACRO_EVENT_PROVIDER_SERIES_TO_CONCEPT.values()))

__all__ = [
    "MACRO_EVENT_CONCEPTS",
    "MACRO_EVENT_PROVIDER_SERIES_TO_CONCEPT",
    "MACRO_EVIDENCE_HISTORY_LIMIT_PER_SERIES",
    "MACRO_EVIDENCE_HISTORY_LOOKBACK_DAYS",
    "MACRO_EVIDENCE_PROJECTION_VERSION",
    "MACRO_IMPORTABLE_PROVIDER_SERIES_TO_CONCEPT",
    "MACRO_MIN_CHART_POINTS",
    "MACRO_PROVIDER_SERIES_SOURCE_PRIORITY",
    "MACRO_PROVIDER_SERIES_TO_CONCEPT",
]
