# scripts/regen_cli_help.py
"""Regenerate docs/generated/cli-help.md from `parallax --help`."""

from __future__ import annotations

import subprocess
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "cli-help.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_cli_help.py — do not hand-edit -->\n\n"


def _help(args: list[str]) -> str:
    return subprocess.check_output(
        ["uv", "run", "parallax", *args, "--help"],
        text=True,
    )


def main() -> None:
    body = ["# CLI Help", "", "## Top level", "", "```", _help([]), "```", ""]
    for group in ("db", "ops"):
        body += [f"## `{group}`", "", "```", _help([group]), "```", ""]
    OUTPUT.write_text(HEADER + "\n".join(body), encoding="utf-8")


if __name__ == "__main__":
    main()
