from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.validate_sdd_artifacts import (  # noqa: E402
    KNOWN_ISSUE_CODES,
    SddFeature,
    SddIssue,
    TaskRecord,
    scan_sdd_features,
    task_dependencies_satisfied,
    validate_sdd_root,
)

OUTPUT = ROOT / "docs" / "generated" / "sdd-work-index.md"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/sdd-work-index.md")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the generated file is stale")
    args = parser.parse_args()

    text = render_index(scan_sdd_features(ROOT), validate_sdd_root(ROOT))
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != text:
            print(
                "docs/generated/sdd-work-index.md is stale; run `uv run python scripts/regen_sdd_work_index.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


def render_index(features: list[SddFeature], issues: list[SddIssue]) -> str:
    feature_counts = Counter(feature.state for feature in features)
    artifact_counts = Counter(
        feature.state for feature in features for artifact in feature.artifacts.values() if not artifact.missing
    )
    issue_counts = Counter({code: 0 for code in KNOWN_ISSUE_CODES})
    issue_counts.update(issue.code for issue in issues)
    issue_map = _issues_by_feature(features, issues)

    lines = [
        "# SDD Work Index",
        "",
        "> Generated by `scripts/regen_sdd_work_index.py`. Do not hand-edit.",
        "",
        (
            "This index is a coordination board for coding agents. SDD artifacts are execution records; "
            "canonical project truth remains in code, root governance docs, domain architecture maps, tests, "
            "and generated contracts."
        ),
        "",
        "## Summary",
        "",
        "| State | Features | Artifacts |",
        "|-------|----------|-----------|",
        f"| `active` | {feature_counts['active']} | {artifact_counts['active']} |",
        f"| `completed` | {feature_counts['completed']} | {artifact_counts['completed']} |",
        "",
        "## Lifecycle Flags",
        "",
        "| Flag | Count | Meaning |",
        "|------|-------|---------|",
    ]
    lines.extend(
        f"| `{code}` | {issue_counts[code]} | {markdown_escape(_issue_meaning(code))} |" for code in KNOWN_ISSUE_CODES
    )

    lines.extend(
        [
            "",
            "## Coordination Board",
            "",
            "| Feature | State | Status | Owner | Worktree | Branch | Factory lanes | Touch set | Conflict set | "
            "Blocked | Verification | Flags | Path |",
            "|---------|-------|--------|-------|----------|--------|---------------|-----------|--------------|"
            "---------|--------------|-------|------|",
        ]
    )
    for feature in sorted(features, key=lambda item: (item.state, item.slug)):
        feature_issues = issue_map.get(feature.slug, [])
        flags = ", ".join(f"`{issue.code}`" for issue in feature_issues) or "-"
        lines.append(
            "| "
            f"`{feature.slug}` | "
            f"`{feature.state}` | "
            f"{markdown_escape(feature.status)} | "
            f"{markdown_escape(feature.owner)} | "
            f"`{markdown_escape(feature.worktree)}` | "
            f"`{markdown_escape(feature.branch)}` | "
            f"{_set_cell(feature.factory_lanes)} | "
            f"{_set_cell(feature.touch_set)} | "
            f"{_set_cell(feature.conflict_set)} | "
            f"{markdown_escape(feature.blocked)} | "
            f"`{feature.verification}` | "
            f"{flags} | "
            f"`{feature.relative_path}` |"
        )

    lines.extend(
        [
            "",
            "## Task Board",
            "",
            "| Feature | Task | Status | Dispatch | Factory lane | Owner | Depends on | Touch set | Conflict set | "
            "Subagent report | Review result | Verification |",
            "|---------|------|--------|----------|--------------|-------|------------|-----------|--------------|"
            "-----------------|---------------|--------------|",
        ]
    )
    for feature in sorted(features, key=lambda item: (item.state, item.slug)):
        lines.extend(_task_row(feature, task) for task in feature.tasks)

    lines.extend(
        [
            "",
            "## Artifacts",
            "",
            "| Feature | State | Artifact | Status | Path |",
            "|---------|-------|----------|--------|------|",
        ]
    )
    for feature in sorted(features, key=lambda item: (item.state, item.slug)):
        for artifact_name, artifact in feature.artifacts.items():
            lines.append(
                f"| `{feature.slug}` | `{feature.state}` | `{artifact_name}` | "
                f"{markdown_escape(artifact.status)} | `{artifact.relative_path}` |"
            )
    lines.append("")
    return "\n".join(lines)


def _issues_by_feature(features: list[SddFeature], issues: list[SddIssue]) -> dict[str, list[SddIssue]]:
    by_feature: dict[str, list[SddIssue]] = defaultdict(list)
    for issue in issues:
        for feature in features:
            if issue.path.startswith(feature.relative_path):
                by_feature[feature.slug].append(issue)
                break
    return by_feature


def _set_cell(values: tuple[str, ...]) -> str:
    return "<br>".join(f"`{markdown_escape(value)}`" for value in values) if values else "-"


def _task_field(task: TaskRecord, field_name: str) -> str:
    value = task.fields.get(field_name, "")
    return value or "-"


def _task_row(feature: SddFeature, task: TaskRecord) -> str:
    return (
        "| "
        f"`{feature.slug}` | "
        f"`{markdown_escape(task.title)}` | "
        f"`{markdown_escape(_task_field(task, 'status'))}` | "
        f"`{_task_dispatch_state(feature, task)}` | "
        f"`{markdown_escape(_task_field(task, 'factory lane'))}` | "
        f"{markdown_escape(_task_field(task, 'owner'))} | "
        f"{markdown_escape(_task_field(task, 'depends on'))} | "
        f"{_task_set_cell(task, 'touch set')} | "
        f"{_task_set_cell(task, 'conflict set')} | "
        f"`{markdown_escape(_task_field(task, 'subagent report'))}` | "
        f"`{markdown_escape(_task_field(task, 'review result'))}` | "
        f"`{markdown_escape(_task_field(task, 'verification'))}` |"
    )


def _task_dispatch_state(feature: SddFeature, task: TaskRecord) -> str:
    status = _task_field(task, "status").strip().lower()
    if feature.state != "active":
        return "closed"
    review_result = _task_field(task, "review result").strip().lower()
    if review_result in {"needs-repair", "blocked"}:
        return review_result
    if status in {"[ ]", "[~]"}:
        if not task_dependencies_satisfied(feature, task):
            return "blocked-by-dependencies"
        return "dispatchable"
    if status == "[x]":
        return "complete"
    if status == "[!]":
        return "blocked"
    return "invalid"


def _task_set_cell(task: TaskRecord, field_name: str) -> str:
    raw = _task_field(task, field_name)
    if raw in {"", "-"}:
        return "-"
    separator = r";" if field_name == "conflict set" else r"[,;]"
    values = tuple(item.strip() for item in re.split(separator, raw.replace("`", "")) if item.strip())
    return _set_cell(values)


def _issue_meaning(code: str) -> str:
    meanings = {
        "review-lifecycle": "Artifact status is not valid for its lane.",
        "artifact-status-mismatch": "Feature artifacts disagree on one lifecycle status.",
        "missing-status": "Artifact is missing a status line in its first 40 lines.",
        "missing-artifact": "Feature directory does not contain the full SDD artifact set.",
        "unexpected-artifact": "Feature directory contains files outside the four canonical artifacts.",
        "missing-gate-section": (
            "Artifact is missing required clarify, checklist, analyze, task, or verification sections."
        ),
        "missing-approval-metadata": "Artifact lacks machine-readable approval or execution metadata.",
        "task-missing-coordination-fields": (
            "Task records lack owner, touch set, conflict set, verification, review, or status fields."
        ),
        "task-invalid-coordination-fields": (
            "Task records contain non-path touch/file fields, non-command verification, invalid status, "
            "or malformed conflict rules."
        ),
        "task-invalid-dependencies": (
            "Task dependencies reference missing task numbers, unsupported syntax, or incomplete prerequisites."
        ),
        "task-missing-agent-loop-fields": (
            "Task records lack factory lane, deterministic constraints, on-demand context, kill criteria, "
            "or eval signal."
        ),
        "task-missing-review-fields": "Task records lack subagent report or parent review result evidence.",
        "task-invalid-review-fields": "Task report/review evidence is inconsistent with delegation, scope, or status.",
        "task-missing-subagent-handoff-artifact": (
            "Delegated task references a subagent handoff artifact that is missing."
        ),
        "task-missing-subagent-report-artifact": (
            "Delegated task references a subagent report artifact that is missing."
        ),
        "task-invalid-subagent-report-artifact": (
            "Delegated task report artifact fails the task-bound report validator."
        ),
        "task-complete-missing-verification-evidence": (
            "Completed task lacks matching verification command evidence with exit code 0."
        ),
        "task-incomplete-in-verified-feature": "Verified feature contains incomplete task status.",
        "verified-missing-check-all": "Verified record lacks successful make check-all evidence.",
        "verified-contradicts-evidence": "Verified record contains text that contradicts final evidence.",
        "verified-unexplained-skips": "Verified record has skipped tests without an acceptable explanation.",
        "superseded-missing-successor": (
            "Superseded record lacks a machine-readable existing successor path."
        ),
        "superseded-successor-mismatch": "Superseded artifacts in one feature disagree on the successor.",
        "active-touch-conflict": "Active features share touch paths without an explicit coordination rule.",
    }
    return meanings[code]


def markdown_escape(value: str) -> str:
    return str(value).replace("|", "\\|")


if __name__ == "__main__":
    raise SystemExit(main())
