# scripts/regen_cli_help.py
"""Regenerate docs/generated/cli-help.md from `tracefold --help`."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "cli-help.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_cli_help.py — do not hand-edit -->\n\n"


def _help(args: list[str]) -> str:
    proc = subprocess.run(
        ["uv", "run", "tracefold", *args, "--help"],
        capture_output=True,
        check=False,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(proc.returncode)
    return proc.stdout


def _render() -> str:
    body = ["# CLI Help", "", "## Top level", "", "```", _help([]), "```", ""]
    for group in ("db", "ops"):
        body += [f"## `{group}`", "", "```", _help([group]), "```", ""]
    return HEADER + "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/cli-help.md from `tracefold --help`")
    parser.add_argument("--check", action="store_true", help="exit non-zero if docs/generated/cli-help.md is stale")
    args = parser.parse_args()

    rendered = _render()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                "docs/generated/cli-help.md is stale; run `uv run python scripts/regen_cli_help.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[1]).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
