from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.validate_sdd_artifacts import (  # noqa: E402
    KNOWN_ISSUE_CODES,
    SddFeature,
    SddIssue,
    scan_sdd_features,
    validate_sdd_root,
)

OUTPUT = ROOT / "docs" / "generated" / "sdd-work-index.md"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/sdd-work-index.md")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the generated file is stale")
    args = parser.parse_args()

    text = render_index(scan_sdd_features(ROOT), validate_sdd_root(ROOT))
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != text:
            print(
                "docs/generated/sdd-work-index.md is stale; run `uv run python scripts/regen_sdd_work_index.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


def render_index(features: list[SddFeature], issues: list[SddIssue]) -> str:
    feature_counts = Counter(feature.state for feature in features)
    artifact_counts = Counter(feature.state for feature in features for _artifact in feature.artifacts.values())
    issue_counts = Counter({code: 0 for code in KNOWN_ISSUE_CODES})
    issue_counts.update(issue.code for issue in issues)
    issue_map = _issues_by_feature(features, issues)

    lines = [
        "# SDD Work Index",
        "",
        "> Generated by `scripts/regen_sdd_work_index.py`. Do not hand-edit.",
        "",
        (
            "This index is a coordination board for coding agents. SDD artifacts are execution records; "
            "canonical project truth remains in code, root governance docs, domain architecture maps, tests, "
            "and generated contracts."
        ),
        "",
        "## Summary",
        "",
        "| State | Features | Artifacts |",
        "|-------|----------|-----------|",
        f"| `active` | {feature_counts['active']} | {artifact_counts['active']} |",
        f"| `completed` | {feature_counts['completed']} | {artifact_counts['completed']} |",
        "",
        "## Lifecycle Flags",
        "",
        "| Flag | Count | Meaning |",
        "|------|-------|---------|",
    ]
    lines.extend(
        f"| `{code}` | {issue_counts[code]} | {markdown_escape(_issue_meaning(code))} |" for code in KNOWN_ISSUE_CODES
    )

    lines.extend(
        [
            "",
            "## Coordination Board",
            "",
            "| Feature | State | Status | Owner | Worktree | Branch | Touch set | Conflict set | "
            "Blocked | Verification | Flags | Path |",
            "|---------|-------|--------|-------|----------|--------|-----------|--------------|"
            "---------|--------------|-------|------|",
        ]
    )
    for feature in sorted(features, key=lambda item: (item.state, item.slug)):
        feature_issues = issue_map.get(feature.slug, [])
        flags = ", ".join(f"`{issue.code}`" for issue in feature_issues) or "-"
        lines.append(
            "| "
            f"`{feature.slug}` | "
            f"`{feature.state}` | "
            f"{markdown_escape(feature.status)} | "
            f"{markdown_escape(feature.owner)} | "
            f"`{markdown_escape(feature.worktree)}` | "
            f"`{markdown_escape(feature.branch)}` | "
            f"{_set_cell(feature.touch_set)} | "
            f"{_set_cell(feature.conflict_set)} | "
            f"{markdown_escape(feature.blocked)} | "
            f"`{feature.verification}` | "
            f"{flags} | "
            f"`{feature.relative_path}` |"
        )

    lines.extend(
        [
            "",
            "## Artifacts",
            "",
            "| Feature | State | Artifact | Status | Path |",
            "|---------|-------|----------|--------|------|",
        ]
    )
    for feature in sorted(features, key=lambda item: (item.state, item.slug)):
        for artifact_name, artifact in feature.artifacts.items():
            lines.append(
                f"| `{feature.slug}` | `{feature.state}` | `{artifact_name}` | "
                f"{markdown_escape(artifact.status)} | `{artifact.relative_path}` |"
            )
    lines.append("")
    return "\n".join(lines)


def _issues_by_feature(features: list[SddFeature], issues: list[SddIssue]) -> dict[str, list[SddIssue]]:
    by_feature: dict[str, list[SddIssue]] = defaultdict(list)
    for issue in issues:
        for feature in features:
            if issue.path.startswith(feature.relative_path):
                by_feature[feature.slug].append(issue)
                break
    return by_feature


def _set_cell(values: tuple[str, ...]) -> str:
    return "<br>".join(f"`{markdown_escape(value)}`" for value in values) if values else "-"


def _issue_meaning(code: str) -> str:
    meanings = {
        "review-lifecycle": "Artifact status is not valid for its lane.",
        "missing-status": "Artifact is missing a status line in its first 40 lines.",
        "missing-artifact": "Feature directory does not contain the full SDD artifact set.",
        "missing-gate-section": (
            "Artifact is missing required clarify, checklist, analyze, task, or verification sections."
        ),
        "missing-approval-metadata": "Artifact lacks machine-readable approval or execution metadata.",
        "task-missing-coordination-fields": (
            "Task records lack owner, touch set, conflict set, verification, review, or status fields."
        ),
        "task-incomplete-in-verified-feature": "Verified feature contains incomplete task status.",
        "verified-missing-check-all": "Verified record lacks successful make check-all evidence.",
        "verified-contradicts-evidence": "Verified record contains text that contradicts final evidence.",
        "verified-unexplained-skips": "Verified record has skipped tests without an acceptable explanation.",
        "superseded-missing-successor": "Superseded record does not name the successor.",
        "active-touch-conflict": "Active features share touch paths without an explicit coordination rule.",
    }
    return meanings[code]


def markdown_escape(value: str) -> str:
    return str(value).replace("|", "\\|")


if __name__ == "__main__":
    raise SystemExit(main())
