"""Regenerate docs/generated/pulse-agent-desk-decisions.md."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "generated" / "pulse-agent-desk-decisions.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_pulse_agent_desk_decisions.py - do not hand-edit -->\n\n"

PLAN = "docs/superpowers/plans/active/2026-05-20-pulse-1h-4h-research-committee-plan-cn.md"
SPEC = "docs/superpowers/specs/active/2026-05-20-pulse-1h-4h-research-committee-cn.md"

RESEARCH_COMMITTEE_DECISIONS = [
    (
        "RC-1 1h/4h primary horizons",
        [
            "Signal Pulse admission is hard-cut to `1h` and `4h`.",
            "The default public lane is `4h/all`; `1h` is the early-confirmation lane.",
            "Short-window Token Radar rows can remain upstream observation for non-Pulse surfaces, "
            "but they are not Pulse Agent admission windows.",
        ],
    ),
    (
        "RC-2 packet-only committee",
        [
            "The Pulse Agent runs a three-stage packet-only research committee: "
            "`signal_analyst`, `bear_case`, and `risk_portfolio_judge`.",
            "Each stage reasons only over the sealed evidence packet and prior committee memo refs.",
            "The final judge writes the public recommendation, thesis, playbook, residual risks, "
            "and cited evidence refs.",
        ],
    ),
    (
        "RC-3 no tool execution",
        [
            "Pulse committee stages do not register tools and do not fetch missing facts.",
            "Missing, stale, or contradictory packet data is represented as data gaps, risk evidence, "
            "abstain, or hidden audit state.",
            "Runtime capacity is controlled by `pulse.pipeline` plus per-stage committee lanes.",
        ],
    ),
    (
        "RC-4 source-quality public gate",
        [
            "Public Signal Pulse rows require independent-source quality.",
            "Matched or watched-source evidence is useful alert context, but it cannot by itself "
            "publish a default discovery row.",
            "`hidden_source_quality` preserves audit visibility without making noisy rows public.",
        ],
    ),
    (
        "RC-5 generated contracts",
        [
            "OpenAPI and TypeScript types are regenerated after API stage/status changes.",
            "Architecture tests assert that removed stage prompt files do not reappear and removed windows "
            "are not advertised for Pulse admission.",
            "Generated docs are owned by this script and must not be hand-edited.",
        ],
    ),
    (
        "RC-6 release evidence",
        [
            "Local tests and contract drift checks are required before commit.",
            "Live rollout verification must prove that new Pulse jobs are created only for the `1h` "
            "and `4h` horizons after the deployment timestamp.",
            "If operator config still contains removed Pulse windows, fix the config file; do not add code "
            "that accepts it.",
        ],
    ),
]


def _render_section(title: str, paragraphs: list[str]) -> list[str]:
    lines = [f"## {title}", ""]
    for paragraph in paragraphs:
        lines.extend([paragraph, ""])
    return lines


def render() -> str:
    lines = [
        "# Pulse Agent Desk Decisions",
        "",
        "Source of truth: deterministic generator script; no runtime database reads.",
        "",
        f"Plan: `{PLAN}`",
        f"Spec: `{SPEC}`",
        "",
        "## Decision Inventory",
        "",
        "| ID | Decision |",
        "|----|----------|",
    ]
    for title, _ in RESEARCH_COMMITTEE_DECISIONS:
        decision_id, decision = title.split(" ", 1)
        lines.append(f"| `{decision_id}` | {decision} |")
    lines.append("")
    lines.append("# Research Committee Decisions")
    lines.append("")
    for title, paragraphs in RESEARCH_COMMITTEE_DECISIONS:
        lines.extend(_render_section(title, paragraphs))
    lines.append("## 决策完成确认")
    lines.append("")
    lines.append("The Pulse 1h/4h research committee decisions are recorded here and regenerated by script.")
    lines.append("")
    return HEADER + "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(dedent(render()), encoding="utf-8")


if __name__ == "__main__":
    main()
