# scripts/regen_db_schema.py
"""Regenerate docs/generated/db-schema.md from Alembic head + pg_catalog introspection.

Requires Postgres reachable via the standard project config.

Import note: the storage module uses psycopg directly (no SQLAlchemy engine).
We follow the same pattern as src/gmgn_twitter_intel/storage/alembic/env.py:
build a postgresql+psycopg URL via local_docker_host_dsn / with_password_from_file
and pass it to sqlalchemy.create_engine for inspection-only access.
"""
from __future__ import annotations

from pathlib import Path

from sqlalchemy import create_engine, inspect

from gmgn_twitter_intel.platform.config.settings import load_settings
from gmgn_twitter_intel.platform.db.postgres_client import local_docker_host_dsn, with_password_from_file

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "db-schema.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_db_schema.py — do not hand-edit -->\n\n"


def _sqlalchemy_url(settings) -> str:  # type: ignore[no-untyped-def]
    dsn = local_docker_host_dsn(
        with_password_from_file(settings.postgres_dsn, settings.postgres_password_file)
    )
    if dsn.startswith("postgresql://"):
        return "postgresql+psycopg://" + dsn.removeprefix("postgresql://")
    return dsn


def main() -> None:
    settings = load_settings(require_ws_token=False)
    engine = create_engine(_sqlalchemy_url(settings), pool_pre_ping=True)
    inspector = inspect(engine)
    body = ["# Database Schema", ""]
    for table in sorted(inspector.get_table_names(schema="public")):
        body.append(f"## `{table}`")
        body.append("")
        body.append("| Column | Type | Nullable | Default |")
        body.append("|--------|------|----------|---------|")
        for col in inspector.get_columns(table, schema="public"):
            body.append(
                f"| `{col['name']}` | `{col['type']}` | "
                f"{col.get('nullable', True)} | `{col.get('default')}` |"
            )
        body.append("")
    OUTPUT.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    engine.dispose()


if __name__ == "__main__":
    main()
