from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.validate_sdd_artifacts import (  # noqa: E402
    SddFeature,
    SddIssue,
    TaskRecord,
    scan_sdd_features,
    validate_sdd_root,
)

OUTPUT = ROOT / "docs" / "generated" / "sdd-work-index.md"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate the active SDD work index")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the generated file is stale")
    args = parser.parse_args()

    text = render_index(scan_sdd_features(ROOT), validate_sdd_root(ROOT))
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != text:
            print(
                "docs/generated/sdd-work-index.md is stale; run `uv run python scripts/regen_sdd_work_index.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


def render_index(features: list[SddFeature], issues: list[SddIssue]) -> str:
    active = sorted((feature for feature in features if feature.state == "active"), key=lambda item: item.slug)
    issue_map = _issues_by_feature(active, issues)
    lines = [
        "# SDD Work Index",
        "",
        "> Generated by `scripts/regen_sdd_work_index.py`. Do not hand-edit.",
        "",
        f"Active features: {len(active)}.",
        "",
        "## Features",
        "",
        "| Feature | Status | Owner | Worktree | Branch | Touch set | Conflict set | Verification | Flags |",
        "|---------|--------|-------|----------|--------|-----------|--------------|--------------|-------|",
    ]
    for feature in active:
        flags = ", ".join(f"`{issue.code}`" for issue in issue_map.get(feature.slug, [])) or "-"
        lines.append(
            f"| `{feature.slug}` | {markdown_escape(feature.status)} | {markdown_escape(feature.owner)} | "
            f"`{markdown_escape(feature.worktree)}` | `{markdown_escape(feature.branch)}` | "
            f"{_set_cell(feature.touch_set)} | {_set_cell(feature.conflict_set)} | "
            f"`{feature.verification}` | {flags} |"
        )

    lines.extend(
        [
            "",
            "## Tasks",
            "",
            "| Feature | Task | Status | Owner | Depends on | Touch set | Conflict set | Verification |",
            "|---------|------|--------|-------|------------|-----------|--------------|--------------|",
        ]
    )
    for feature in active:
        lines.extend(_task_row(feature, task) for task in feature.tasks)
    lines.append("")
    return "\n".join(lines)


def _issues_by_feature(features: list[SddFeature], issues: list[SddIssue]) -> dict[str, list[SddIssue]]:
    by_feature: dict[str, list[SddIssue]] = defaultdict(list)
    for issue in issues:
        for feature in features:
            if issue.path.startswith(feature.relative_path):
                by_feature[feature.slug].append(issue)
                break
    return by_feature


def _set_cell(values: tuple[str, ...]) -> str:
    return "<br>".join(f"`{markdown_escape(value)}`" for value in values) if values else "-"


def _task_field(task: TaskRecord, field_name: str) -> str:
    return task.fields.get(field_name, "") or "-"


def _task_set_cell(task: TaskRecord, field_name: str) -> str:
    raw = _task_field(task, field_name)
    if raw == "-":
        return "-"
    values = tuple(item.strip() for item in re.split(r"[,;]", raw.replace("`", "")) if item.strip())
    return _set_cell(values)


def _task_row(feature: SddFeature, task: TaskRecord) -> str:
    return (
        f"| `{feature.slug}` | `{markdown_escape(task.title)}` | "
        f"`{markdown_escape(_task_field(task, 'status'))}` | "
        f"{markdown_escape(_task_field(task, 'owner'))} | "
        f"{markdown_escape(_task_field(task, 'depends on'))} | "
        f"{_task_set_cell(task, 'touch set')} | {_task_set_cell(task, 'conflict set')} | "
        f"`{markdown_escape(_task_field(task, 'verification'))}` |"
    )


def markdown_escape(value: str) -> str:
    return str(value).replace("|", "\\|")


if __name__ == "__main__":
    raise SystemExit(main())
