# scripts/regen_ws_protocol.py
"""Regenerate docs/generated/ws-protocol.md by introspecting api/ws.py message types."""
from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WS_FILE = ROOT / "src" / "gmgn_twitter_intel" / "app" / "surfaces" / "api" / "ws.py"
OUTPUT = ROOT / "docs" / "generated" / "ws-protocol.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_ws_protocol.py — do not hand-edit -->\n\n"


def _collect_classes(tree: ast.AST) -> list[tuple[str, str]]:
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node) or ""
            names.append((node.name, doc.splitlines()[0] if doc else ""))
    return names


def main() -> None:
    tree = ast.parse(WS_FILE.read_text(encoding="utf-8"))
    rows = _collect_classes(tree)
    body = ["# WebSocket Protocol", "", f"Source: `{WS_FILE.relative_to(ROOT).as_posix()}`", "",
            "| Message class | Doc |", "|---------------|-----|"]
    for name, doc in sorted(rows):
        body.append(f"| `{name}` | {doc} |")
    OUTPUT.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
