# scripts/regen_score_versions.py
"""Regenerate docs/generated/score-versions.md by scanning src/ for score_version literals."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUTPUT = ROOT / "docs" / "generated" / "score-versions.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_score_versions.py — do not hand-edit -->\n\n"
PATTERN = re.compile(r'score_version\s*=\s*[\'"]([^\'"]+)[\'"]')


def main() -> None:
    rows: list[tuple[str, str, int, str]] = []
    for path in sorted(SRC.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for match in PATTERN.finditer(line):
                rows.append((match.group(1), rel, lineno, line.strip()))  # noqa: PERF401 -- triple-nested loop; extend() not applicable
    body = ["# Score Versions", "", "| Version | File | Line | Context |", "|---------|------|------|---------|"]
    for version, rel, lineno, context in sorted(rows):
        body.append(f"| `{version}` | `{rel}` | {lineno} | `{context}` |")
    OUTPUT.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
