"""Regenerate docs/generated/pulse-agent-desk-decisions.md."""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "generated" / "pulse-agent-desk-decisions.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_pulse_agent_desk_decisions.py - do not hand-edit -->\n\n"

REFERENCES = (
    "docs/AGENT_EXECUTION.md",
    "docs/WORKERS.md",
    "src/parallax/domains/pulse_lab/ARCHITECTURE.md",
    "src/parallax/platform/agent_execution.py",
)

PULSE_AGENT_DECISIONS = [
    (
        "PA-1 1h/4h primary horizons",
        [
            "Signal Pulse admission is hard-cut to `1h` and `4h`.",
            "The default public lane is `4h/all`; `1h` is the early-confirmation lane.",
            "Short-window Token Radar rows can remain upstream observation for non-Pulse surfaces, "
            "but they are not Pulse Agent admission windows.",
        ],
    ),
    (
        "PA-2 packet-only workflow",
        [
            "The Pulse Agent runs one packet-only `pulse_decision` stage.",
            "The stage reasons only over the sealed evidence packet, evidence gate, source quality summary, "
            "and recommendation constraints.",
            "The final decision writes the public recommendation, thesis, playbook, residual risks, "
            "and cited evidence refs.",
        ],
    ),
    (
        "PA-3 no tool execution",
        [
            "Pulse agent stages do not register tools and do not fetch missing facts.",
            "Missing, stale, or contradictory packet data is represented as data gaps, risk evidence, "
            "abstain, or hidden audit state.",
            "Runtime capacity is controlled by the single `pulse.decision` lane.",
        ],
    ),
    (
        "PA-4 source-quality public gate",
        [
            "Public Signal Pulse rows require independent-source quality.",
            "Matched or watched-source evidence is useful alert context, but it cannot by itself "
            "publish a default discovery row.",
            "`hidden_source_quality` preserves audit visibility without making noisy rows public.",
        ],
    ),
    (
        "PA-5 generated contracts",
        [
            "OpenAPI and TypeScript types are regenerated after API stage/status changes.",
            "Architecture tests assert that removed stage prompt files do not reappear and removed windows "
            "are not advertised for Pulse admission.",
            "Generated docs are owned by this script and must not be hand-edited.",
        ],
    ),
    (
        "PA-6 release evidence",
        [
            "Local tests and contract drift checks are required before commit.",
            "Live rollout verification must prove that new Pulse jobs are created only for the `1h` "
            "and `4h` horizons after the deployment timestamp.",
            "If operator config still contains removed Pulse windows, fix the config file; do not add code "
            "that accepts it.",
        ],
    ),
]


def _render_section(title: str, paragraphs: list[str]) -> list[str]:
    lines = [f"## {title}", ""]
    for paragraph in paragraphs:
        lines.extend([paragraph, ""])
    return lines


def render() -> str:
    lines = [
        "# Pulse Agent Desk Decisions",
        "",
        "Source of truth: deterministic generator script; no runtime database reads.",
        "",
        "Current references:",
        *[f"- `{reference}`" for reference in REFERENCES],
        "",
        "## Decision Inventory",
        "",
        "| ID | Decision |",
        "|----|----------|",
    ]
    for title, _ in PULSE_AGENT_DECISIONS:
        decision_id, decision = title.split(" ", 1)
        lines.append(f"| `{decision_id}` | {decision} |")
    lines.append("")
    lines.append("# Pulse Agent Decisions")
    lines.append("")
    for title, paragraphs in PULSE_AGENT_DECISIONS:
        lines.extend(_render_section(title, paragraphs))
    lines.append("## 决策完成确认")
    lines.append("")
    lines.append("The Pulse 1h/4h agent workflow decisions are recorded here and regenerated by script.")
    lines.append("")
    return HEADER + "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/pulse-agent-desk-decisions.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/generated/pulse-agent-desk-decisions.md is stale",
    )
    args = parser.parse_args()

    rendered = dedent(render())
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                "docs/generated/pulse-agent-desk-decisions.md is stale; "
                "run `uv run python scripts/regen_pulse_agent_desk_decisions.py`.",
            )
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[1]).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
