"""Regenerate docs/generated/pulse-agent-desk-decisions.md."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "generated" / "pulse-agent-desk-decisions.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_pulse_agent_desk_decisions.py - do not hand-edit -->\n\n"

PLAN = "docs/superpowers/plans/active/2026-05-16-pulse-agent-desk-redesign-plan-cn.md"
SPEC = "docs/superpowers/specs/active/2026-05-16-pulse-agent-desk-redesign-cn.md"
HARDENING_PLAN = "docs/superpowers/plans/active/2026-05-17-pulse-agent-desk-redesign-hardening-plan-cn.md"

ORIGINAL_DECISIONS = [
    (
        "OQ-1 Investigator tool call 上限",
        [
            "锁定 `cex=3, meme=5`，配置写入 `workers.yaml` 的 "
            "`pulse_candidate.investigator_max_tool_calls.{cex,meme}`。",
            "理由: 与 spec §4.4 默认值一致；cex 信号高质量低频，不需要太多 tool round-trip；"
            "meme 信号低质量高频且叙事更模糊，保留更宽预算。Phase 1 上线 7 天后看实际 "
            "`tool_calls_count` 分布再调整。",
            "实施位置: Task 4 工具内 counter + Task 6 client 读 workers.yaml + "
            "`gmgn-twitter-intel init` 默认模板。",
        ],
    ),
    (
        "OQ-2 DecisionMaker fallback tool",
        [
            "锁定启用 `get_target_recent_tweets`，`max_turns=3`。",
            "理由: DecisionMaker 在 Investigator observation 不足时可补查关键证据，避免错误锚定。"
            "`max_turns=3` 覆盖 1 次 tool call、1 次结构化输出、1 次 fallback retry。"
            "Phase 1 上线后若 DecisionMaker tool call 命中率 <5%，下个迭代禁用。",
            "2026-05-17 hardening clarification: fallback budget remains observe-only; it is measured and "
            "audited, but not used as an automatic runtime budget escalation.",
        ],
    ),
    (
        "OQ-3 GMGN description backfill",
        [
            "实施时验证发现 GMGN OpenAPI 不返回 description 字段，mapper 链路已正确传递字段，"
            "DB 中 description=NULL 不是 mapper bug。",
            "锁定路线: 跳过 mapper 修改；官方叙事降级为 GMGN 实际提供字段 "
            "`symbol / name / website / twitter_username / telegram / banner_url / logo_url`。",
            "`get_official_token_profile` 暴露这些字段并显式注明 "
            "`description: null, description_source_available: false`；prompt 在 description 为 null 时"
            "结合 name/symbol/twitter_username/website 推断官方定位；不做 backfill。",
        ],
    ),
    (
        "OQ-4 `_FORBIDDEN_EXECUTION_RE` 反测",
        [
            "锁定 31 个候选字段名/值全部通过反测，0 误伤。",
            "覆盖字段包含 `has_playbook`、`watch_signals`、`exit_triggers`、"
            "`monitoring_horizon`、`investigator`、`decision_maker`、叙事枚举值和中文 watch/exit 文案。",
            "结论: 无字段名/值需改名。Pydantic `_reject_execution_language` 验证器继续对 playbook、"
            "watch_signals、exit_triggers 承担运行时校验。",
        ],
    ),
    (
        "OQ-5 `pulse_agent_runs.outcome` `abstain_critic_veto` enum 值处置",
        [
            "锁定保留作历史只读，不动 CHECK。",
            "理由: 老 outcome 行仍需可读，DROP CHECK 重建会引入 immediate-validate 风险；"
            "新写路径已不再产生该值；enum 残留仅表示 CHECK 允许的历史合法值。",
            "实施位置: 不做 alembic 改动；Task 10 grep 防御允许该值出现在历史读路径中。",
        ],
    ),
    (
        "OQ-6 prompt 文件命名",
        [
            "锁定 `prompts/{investigator,decision_maker}.md` 单文件，路由段落内联。",
            "理由: KISS；复用现有 anti-injection prefix 与角色定位段；prompt diff 更容易 review；"
            "loader 实现简单。",
            "实施位置: `prompt_loader.py` + 2 个 markdown 文件。",
        ],
    ),
]

HARDENING_DECISIONS = [
    (
        "HD-1 fallback budget observe-only",
        [
            "Fallback budget is an observed/audited fact, not a runtime authority to spend extra tool turns.",
            "The hardening pass preserves the original OQ-2 fallback capability while keeping budget semantics "
            "bounded and reviewable.",
        ],
    ),
    (
        "HD-2 detail UI includes v2 decision",
        [
            "Pulse Agent Desk detail UI must expose the v2 decision surface so operators can inspect the "
            "DecisionMaker result without relying only on list-row summaries.",
        ],
    ),
    (
        "HD-3 generated script owns this file",
        [
            "`docs/generated/pulse-agent-desk-decisions.md` is owned by "
            "`scripts/regen_pulse_agent_desk_decisions.py`.",
            "Edits to decisions should update the generator source and rerun `make docs-generated`; the generated "
            "Markdown is not hand-maintained.",
        ],
    ),
    (
        "HD-4 live canary remains release gate",
        [
            "Live canary verification remains a release gate for Pulse Agent Desk hardening.",
            "Generated documentation does not replace production-facing canary evidence.",
        ],
    ),
]


def _render_section(title: str, paragraphs: list[str]) -> list[str]:
    lines = [f"## {title}", ""]
    for paragraph in paragraphs:
        lines.extend([paragraph, ""])
    return lines


def render() -> str:
    lines = [
        "# Pulse Agent Desk Decisions",
        "",
        "Source of truth: deterministic generator script; no runtime database reads.",
        "",
        f"Original plan: `{PLAN}`",
        f"Original spec: `{SPEC}`",
        f"Hardening plan: `{HARDENING_PLAN}`",
        "",
        "## Decision Inventory",
        "",
        "| ID | Decision |",
        "|----|----------|",
    ]
    for title, _ in ORIGINAL_DECISIONS + HARDENING_DECISIONS:
        decision_id, decision = title.split(" ", 1)
        lines.append(f"| `{decision_id}` | {decision} |")
    lines.append("")
    lines.append("# Original Open Questions")
    lines.append("")
    for title, paragraphs in ORIGINAL_DECISIONS:
        lines.extend(_render_section(title, paragraphs))
    lines.append("# 2026-05-17 Hardening Decisions")
    lines.append("")
    for title, paragraphs in HARDENING_DECISIONS:
        lines.extend(_render_section(title, paragraphs))
    lines.append("## 决策完成确认")
    lines.append("")
    lines.append(
        "The six original OQ decisions and the 2026-05-17 hardening decisions are recorded here and "
        "regenerated by script."
    )
    lines.append("")
    return HEADER + "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(dedent(render()), encoding="utf-8")


if __name__ == "__main__":
    main()
