from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUPERPOWERS = ROOT / "docs" / "superpowers"
OUTPUT = ROOT / "docs" / "generated" / "agent-work-index.md"

STATUS_RE = re.compile(r"^\s*(?:\*\*)?Status(?:\*\*)?\s*:\s*(.+?)\s*$", re.IGNORECASE)
COMPLETE_STATUS_RE = re.compile(r"\b(complete|completed|implemented|verified|merged)\b", re.IGNORECASE)
SUPERSEDED_STATUS_RE = re.compile(r"\bsuperseded\b", re.IGNORECASE)


@dataclass(frozen=True)
class WorkItem:
    lane: str
    state: str
    path: Path
    status: str
    flags: tuple[str, ...]

    @property
    def relative_path(self) -> str:
        return self.path.relative_to(ROOT).as_posix()


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/agent-work-index.md")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the generated file is stale")
    args = parser.parse_args()

    text = render_index(scan_work_items())
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != text:
            print(
                "docs/generated/agent-work-index.md is stale; run `uv run python scripts/regen_agent_work_index.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


def scan_work_items() -> list[WorkItem]:
    items: list[WorkItem] = []
    for lane in ("specs", "plans"):
        for state in ("active", "completed"):
            root = SUPERPOWERS / lane / state
            for path in sorted(root.rglob("*.md")):
                status = extract_status(path)
                flags = lifecycle_flags(state=state, status=status)
                items.append(WorkItem(lane=lane, state=state, path=path, status=status, flags=flags))
    return items


def extract_status(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines()[:40]:
        match = STATUS_RE.match(line)
        if match:
            return normalize_cell(match.group(1))
    return "unspecified"


def lifecycle_flags(*, state: str, status: str) -> tuple[str, ...]:
    flags: list[str] = []
    if state == "active" and COMPLETE_STATUS_RE.search(status) and not SUPERSEDED_STATUS_RE.search(status):
        flags.append("review-lifecycle")
    if status == "unspecified":
        flags.append("missing-status")
    return tuple(flags)


def render_index(items: list[WorkItem]) -> str:
    counts = Counter((item.lane, item.state) for item in items)
    flag_counts = Counter(flag for item in items for flag in item.flags)
    lines = [
        "# Agent Work Index",
        "",
        "> Generated by `scripts/regen_agent_work_index.py`. Do not hand-edit.",
        "",
        (
            "This index makes the planning lane visible to coding agents. Active files are working "
            "artefacts, not canonical truth; verify them against docs and code before use."
        ),
        "",
        "## Summary",
        "",
        "| Lane | Active | Completed |",
        "|------|--------|-----------|",
    ]
    lines.extend(
        f"| `{lane}` | {counts[(lane, 'active')]} | {counts[(lane, 'completed')]} |" for lane in ("specs", "plans")
    )

    lines.extend(
        [
            "",
            "## Lifecycle Flags",
            "",
            "| Flag | Count | Meaning |",
            "|------|-------|---------|",
            (
                "| `review-lifecycle` | "
                f"{flag_counts['review-lifecycle']} | Active file has a status that looks "
                "complete/implemented/verified and should be reviewed for migration to "
                "`completed/` or marked superseded. |"
            ),
            (
                "| `missing-status` | "
                f"{flag_counts['missing-status']} | File has no status line in its first 40 lines. |"
            ),
            "",
            "## Items",
            "",
            "| Lane | State | Status | Flags | Path |",
            "|------|-------|--------|-------|------|",
        ]
    )
    for item in items:
        flags = ", ".join(f"`{flag}`" for flag in item.flags) or "-"
        lines.append(
            f"| `{item.lane}` | `{item.state}` | {markdown_escape(item.status)} | {flags} | `{item.relative_path}` |"
        )
    lines.append("")
    return "\n".join(lines)


def normalize_cell(value: str) -> str:
    normalized = " ".join(str(value).strip().split())
    return normalized.replace("|", "\\|") or "unspecified"


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    raise SystemExit(main())
