from __future__ import annotations

SIGNAL_PULSE_WINDOWS = ("1h", "4h")
SIGNAL_PULSE_WINDOW_SET = frozenset(SIGNAL_PULSE_WINDOWS)
SIGNAL_PULSE_DEFAULT_WINDOW = "4h"


__all__ = [
    "SIGNAL_PULSE_DEFAULT_WINDOW",
    "SIGNAL_PULSE_WINDOWS",
    "SIGNAL_PULSE_WINDOW_SET",
]
