from __future__ import annotations

from dataclasses import dataclass

from parallax.domains.macro_intel._constants import MACRO_EVENT_CONCEPTS


class UnsupportedMacroModuleError(ValueError):
    def __init__(self, module_id: str) -> None:
        super().__init__(f"Unsupported macro module: {module_id}")
        self.code = "unsupported_macro_module"
        self.module_id = module_id


@dataclass(frozen=True)
class MacroChartSpec:
    chart_id: str
    concept_keys: tuple[str, ...] = ()


@dataclass(frozen=True)
class MacroTableSpec:
    table_id: str
    concept_keys: tuple[str, ...] = ()


@dataclass(frozen=True)
class MacroModuleConfig:
    module_id: str
    route_path: str
    title: str
    subtitle: str
    question: str
    section: str
    required_concepts: tuple[str, ...]
    optional_concepts: tuple[str, ...]
    chart_specs: tuple[MacroChartSpec, ...]
    table_specs: tuple[MacroTableSpec, ...]
    related_routes: tuple[str, ...]


MACRO_MODULE_IDS = (
    "overview",
    "assets",
    "assets/equities",
    "assets/bonds",
    "assets/commodities",
    "assets/fx",
    "assets/crypto",
    "rates/fed-funds",
    "rates/yield-curve",
    "rates/real-rates",
    "liquidity/rrp-tga",
    "economy/gdp",
    "economy/employment",
    "economy/inflation",
    "volatility/vix",
    "credit/stress",
)


_MODULE_CONFIGS = {
    "overview": MacroModuleConfig(
        module_id="overview",
        route_path="/macro",
        title="宏观总览",
        subtitle="跨资产、利率、波动率与信用链条",
        question="宏观链条现在是在支持风险资产，还是提示降风险？",
        section="overview",
        required_concepts=(),
        optional_concepts=("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas", *MACRO_EVENT_CONCEPTS),
        chart_specs=(MacroChartSpec("macro_regime", ("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas")),),
        table_specs=(MacroTableSpec("panel_scorecard", ("asset:spx", "rates:dgs10", "vol:vix", "credit:hy_oas")),),
        related_routes=(
            "/macro/assets/equities",
            "/macro/rates/fed-funds",
            "/macro/liquidity/rrp-tga",
            "/macro/volatility/vix",
            "/macro/credit/stress",
        ),
    ),
    "assets": MacroModuleConfig(
        module_id="assets",
        route_path="/macro/assets",
        title="大类资产",
        subtitle="股票、债券、商品、美元与加密资产总览",
        question="今天跨资产链条是在支持 risk-on，还是提示防守？",
        section="assets",
        required_concepts=("asset:spx", "rates:dgs10", "fx:dxy", "commodity:wti_futures", "crypto:btc"),
        optional_concepts=(
            "asset:ndx",
            "asset:dji",
            "asset:rut",
            "asset:tlt",
            "asset:hyg",
            "asset:lqd",
            "commodity:gold_futures",
            "commodity:silver_futures",
            "commodity:natgas_futures",
            "commodity:copper_futures",
            "fx:eurusd",
            "fx:gbpusd",
            "fx:usdjpy",
            "fx:usdcny",
            "fx:usdkrw",
            "crypto:eth",
            "vol:vix",
            "credit:hy_oas",
        ),
        chart_specs=(
            MacroChartSpec(
                "asset_cross_market_snapshot",
                ("asset:spx", "asset:tlt", "commodity:gold_futures", "fx:dxy", "commodity:wti_futures", "crypto:btc"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "asset_group_snapshot",
                (
                    "asset:spx",
                    "asset:ndx",
                    "asset:dji",
                    "asset:rut",
                    "asset:tlt",
                    "asset:hyg",
                    "asset:lqd",
                    "commodity:gold_futures",
                    "commodity:silver_futures",
                    "commodity:wti_futures",
                    "commodity:natgas_futures",
                    "commodity:copper_futures",
                    "fx:dxy",
                    "fx:eurusd",
                    "fx:gbpusd",
                    "fx:usdjpy",
                    "fx:usdcny",
                    "fx:usdkrw",
                    "crypto:btc",
                    "crypto:eth",
                ),
            ),
        ),
        related_routes=(
            "/macro/assets/equities",
            "/macro/assets/bonds",
            "/macro/assets/commodities",
            "/macro/assets/fx",
            "/macro/assets/crypto",
        ),
    ),
    "assets/equities": MacroModuleConfig(
        module_id="assets/equities",
        route_path="/macro/assets/equities",
        title="美股风险",
        subtitle="指数与 ETF 风险偏好确认",
        question="美股领导力是在确认加密 beta，还是开始拖累风险资产？",
        section="assets",
        required_concepts=("asset:spx",),
        optional_concepts=(
            "asset:gspc",
            "asset:nasdaq",
            "asset:ndx",
            "asset:dji",
            "asset:rut",
            "asset:spy",
            "asset:qqq",
            "asset:iwm",
            "asset:dia",
            "asset:efa",
            "asset:eem",
            "asset:smh",
            "asset:soxx",
            "positioning:sp500_net_noncommercial",
        ),
        chart_specs=(
            MacroChartSpec(
                "equity_proxy_performance",
                (
                    "asset:spx",
                    "asset:gspc",
                    "asset:nasdaq",
                    "asset:spy",
                    "asset:qqq",
                    "asset:iwm",
                    "asset:dia",
                    "asset:eem",
                    "asset:smh",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "equity_proxy_snapshot",
                (
                    "asset:spx",
                    "asset:gspc",
                    "asset:nasdaq",
                    "asset:ndx",
                    "asset:dji",
                    "asset:rut",
                    "asset:spy",
                    "asset:qqq",
                    "asset:iwm",
                    "asset:dia",
                    "asset:efa",
                    "asset:eem",
                    "asset:smh",
                    "asset:soxx",
                    "positioning:sp500_net_noncommercial",
                ),
            ),
        ),
        related_routes=("/macro/assets/bonds", "/macro/volatility/vix"),
    ),
    "assets/bonds": MacroModuleConfig(
        module_id="assets/bonds",
        route_path="/macro/assets/bonds",
        title="债券资产",
        subtitle="久期、通胀保护、综合债与信用确认",
        question="债券市场是在释放久期压力，还是确认避险需求？",
        section="assets",
        required_concepts=("asset:tlt",),
        optional_concepts=(
            "asset:shy",
            "asset:ief",
            "asset:tip",
            "asset:bnd",
            "asset:hyg",
            "asset:jnk",
            "asset:lqd",
            "credit:hy_oas",
            "credit:ig_oas",
        ),
        chart_specs=(
            MacroChartSpec(
                "bond_proxy_performance",
                ("asset:shy", "asset:ief", "asset:tlt", "asset:tip", "asset:bnd"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "bond_proxy_snapshot",
                (
                    "asset:shy",
                    "asset:ief",
                    "asset:tlt",
                    "asset:tip",
                    "asset:bnd",
                    "asset:hyg",
                    "asset:jnk",
                    "asset:lqd",
                ),
            ),
        ),
        related_routes=("/macro/assets/equities", "/macro/rates/fed-funds", "/macro/credit/stress"),
    ),
    "assets/commodities": MacroModuleConfig(
        module_id="assets/commodities",
        route_path="/macro/assets/commodities",
        title="商品冲击",
        subtitle="能源、贵金属、铜与通胀脉冲",
        question="商品价格是在制造通胀压力，还是只是局部供需扰动？",
        section="assets",
        required_concepts=("commodity:wti_futures",),
        optional_concepts=(
            "commodity:wti",
            "commodity:brent",
            "commodity:natgas",
            "commodity:gold_futures",
            "commodity:silver_futures",
            "commodity:natgas_futures",
            "commodity:copper_futures",
            "asset:gld",
            "asset:slv",
            "asset:uso",
            "asset:ung",
            "asset:cper",
        ),
        chart_specs=(
            MacroChartSpec(
                "commodity_proxy_performance",
                ("commodity:wti_futures", "commodity:brent", "commodity:natgas_futures", "asset:gld", "asset:uso"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "commodity_proxy_snapshot",
                (
                    "commodity:wti_futures",
                    "commodity:wti",
                    "commodity:brent",
                    "commodity:natgas",
                    "commodity:gold_futures",
                    "commodity:silver_futures",
                    "commodity:natgas_futures",
                    "commodity:copper_futures",
                    "asset:gld",
                    "asset:slv",
                    "asset:uso",
                    "asset:ung",
                    "asset:cper",
                ),
            ),
        ),
        related_routes=("/macro/assets/equities", "/macro/assets/fx"),
    ),
    "assets/fx": MacroModuleConfig(
        module_id="assets/fx",
        route_path="/macro/assets/fx",
        title="美元压力",
        subtitle="DXY、广义美元、主要汇率与货币 ETF",
        question="美元是在收紧离岸流动性，还是给风险资产让路？",
        section="assets",
        required_concepts=("fx:dxy",),
        optional_concepts=(
            "fx:broad_dollar",
            "fx:fred_eurusd",
            "fx:fred_usdjpy",
            "fx:fred_usdcny",
            "fx:fred_gbpusd",
            "fx:eurusd",
            "fx:gbpusd",
            "fx:usdjpy",
            "fx:usdcny",
            "fx:usdkrw",
            "asset:uup",
            "asset:fxe",
            "asset:fxy",
        ),
        chart_specs=(
            MacroChartSpec(
                "fx_proxy_performance",
                ("fx:dxy", "fx:broad_dollar", "asset:uup", "fx:eurusd", "fx:usdcny"),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "fx_proxy_snapshot",
                (
                    "fx:dxy",
                    "fx:broad_dollar",
                    "fx:fred_eurusd",
                    "fx:fred_usdjpy",
                    "fx:fred_usdcny",
                    "fx:fred_gbpusd",
                    "fx:eurusd",
                    "fx:gbpusd",
                    "fx:usdjpy",
                    "fx:usdcny",
                    "fx:usdkrw",
                    "asset:uup",
                    "asset:fxe",
                    "asset:fxy",
                ),
            ),
        ),
        related_routes=("/macro/assets/equities", "/macro/liquidity/rrp-tga"),
    ),
    "assets/crypto": MacroModuleConfig(
        module_id="assets/crypto",
        route_path="/macro/assets/crypto",
        title="加密资产",
        subtitle="BTC / ETH 宏观 beta",
        question="BTC/ETH 是在确认宏观 risk-on，还是只是自身波动？",
        section="assets",
        required_concepts=("crypto:btc",),
        optional_concepts=(
            "crypto:eth",
            "crypto_derivatives:okx_btc_oi_usd",
            "crypto_derivatives:okx_btc_funding",
            "crypto_derivatives:okx_btc_basis",
            "crypto_derivatives:okx_eth_oi_usd",
            "crypto_derivatives:okx_eth_funding",
            "crypto_derivatives:okx_eth_basis",
            "crypto_derivatives:deribit_btc_oi_usd",
            "crypto_derivatives:deribit_btc_funding_8h",
            "crypto_derivatives:deribit_btc_basis",
            "crypto_derivatives:deribit_btc_vol_index",
            "crypto_derivatives:deribit_eth_oi_usd",
            "crypto_derivatives:deribit_eth_funding_8h",
            "crypto_derivatives:deribit_eth_basis",
            "crypto_derivatives:deribit_eth_vol_index",
        ),
        chart_specs=(MacroChartSpec("crypto_proxy_performance", ("crypto:btc", "crypto:eth")),),
        table_specs=(
            MacroTableSpec(
                "crypto_proxy_snapshot",
                (
                    "crypto:btc",
                    "crypto:eth",
                    "crypto_derivatives:okx_btc_oi_usd",
                    "crypto_derivatives:okx_btc_funding",
                    "crypto_derivatives:okx_btc_basis",
                    "crypto_derivatives:okx_eth_oi_usd",
                    "crypto_derivatives:okx_eth_funding",
                    "crypto_derivatives:okx_eth_basis",
                    "crypto_derivatives:deribit_btc_oi_usd",
                    "crypto_derivatives:deribit_btc_funding_8h",
                    "crypto_derivatives:deribit_btc_basis",
                    "crypto_derivatives:deribit_btc_vol_index",
                    "crypto_derivatives:deribit_eth_oi_usd",
                    "crypto_derivatives:deribit_eth_funding_8h",
                    "crypto_derivatives:deribit_eth_basis",
                    "crypto_derivatives:deribit_eth_vol_index",
                ),
            ),
        ),
        related_routes=("/macro/assets/equities", "/macro/volatility/vix"),
    ),
    "rates/fed-funds": MacroModuleConfig(
        module_id="rates/fed-funds",
        route_path="/macro/rates/fed-funds",
        title="联邦基金与走廊",
        subtitle="目标区间、EFFR、IORB、SOFR 与月均联邦基金",
        question="政策走廊是否稳定，隔夜融资是否溢出目标区间？",
        section="rates",
        required_concepts=("fed:target_upper", "fed:target_lower", "fed:effr", "fed:iorb"),
        optional_concepts=(
            "fed:dff",
            "fed:fedfunds",
            "fed:sofr_30d",
            "liquidity:sofr",
            "fed:obfr",
            "fed:effr_volume",
            "fed:obfr_volume",
        ),
        chart_specs=(
            MacroChartSpec(
                "fed_funds_corridor",
                (
                    "fed:target_upper",
                    "fed:target_lower",
                    "fed:dff",
                    "fed:effr",
                    "fed:obfr",
                    "fed:iorb",
                    "liquidity:sofr",
                    "fed:sofr_30d",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "fed_funds_snapshot",
                (
                    "fed:target_upper",
                    "fed:target_lower",
                    "fed:dff",
                    "fed:effr",
                    "fed:obfr",
                    "fed:iorb",
                    "liquidity:sofr",
                    "fed:sofr_30d",
                    "fed:effr_volume",
                    "fed:obfr_volume",
                ),
            ),
        ),
        related_routes=("/macro/liquidity/rrp-tga",),
    ),
    "rates/yield-curve": MacroModuleConfig(
        module_id="rates/yield-curve",
        route_path="/macro/rates/yield-curve",
        title="收益率曲线",
        subtitle="1M 到 30Y 的曲线形态与期限利差",
        question="曲线形态是在交易衰退压力，还是交易期限溢价？",
        section="rates",
        required_concepts=("rates:dgs2", "rates:dgs10"),
        optional_concepts=(
            "rates:dgs1mo",
            "rates:dgs3mo",
            "rates:dgs6mo",
            "rates:dgs1",
            "rates:dgs3",
            "rates:dgs5",
            "rates:dgs7",
            "rates:dgs20",
            "rates:dgs30",
            "rates:10y2y",
            "rates:10y3m",
        ),
        chart_specs=(
            MacroChartSpec(
                "yield_curve",
                (
                    "rates:dgs1mo",
                    "rates:dgs3mo",
                    "rates:dgs6mo",
                    "rates:dgs1",
                    "rates:dgs2",
                    "rates:dgs3",
                    "rates:dgs5",
                    "rates:dgs7",
                    "rates:dgs10",
                    "rates:dgs20",
                    "rates:dgs30",
                ),
            ),
        ),
        table_specs=(MacroTableSpec("curve_spreads", ("rates:10y2y", "rates:10y3m", "rates:dgs10", "rates:dgs30")),),
        related_routes=("/macro/rates/fed-funds", "/macro/rates/real-rates"),
    ),
    "rates/real-rates": MacroModuleConfig(
        module_id="rates/real-rates",
        route_path="/macro/rates/real-rates",
        title="实际利率",
        subtitle="5Y/10Y/30Y TIPS 实际收益率与通胀补偿",
        question="实际利率是在压制成长估值，还是通胀预期主导？",
        section="rates",
        required_concepts=("rates:real_10y",),
        optional_concepts=(
            "rates:real_5y",
            "rates:real_30y",
            "inflation:5y_breakeven",
            "inflation:10y_breakeven",
            "inflation:5y5y_forward",
        ),
        chart_specs=(
            MacroChartSpec(
                "real_rates",
                (
                    "rates:real_5y",
                    "rates:real_10y",
                    "rates:real_30y",
                    "inflation:5y_breakeven",
                    "inflation:10y_breakeven",
                    "inflation:5y5y_forward",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "real_rates_snapshot",
                (
                    "rates:real_5y",
                    "rates:real_10y",
                    "rates:real_30y",
                    "inflation:5y_breakeven",
                    "inflation:10y_breakeven",
                    "inflation:5y5y_forward",
                ),
            ),
        ),
        related_routes=("/macro/rates/fed-funds", "/macro/rates/yield-curve", "/macro/economy/inflation"),
    ),
    "liquidity/rrp-tga": MacroModuleConfig(
        module_id="liquidity/rrp-tga",
        route_path="/macro/liquidity/rrp-tga",
        title="RRP / TGA",
        subtitle="财政现金、逆回购与净流动性代理",
        question="TGA 与 RRP 是否正在吸收市场流动性？",
        section="liquidity",
        required_concepts=("liquidity:on_rrp", "liquidity:tga"),
        optional_concepts=(
            "liquidity:fed_assets",
            "liquidity:reserve_balances",
            "liquidity:sofr",
            "liquidity:bgcr",
            "liquidity:tgcr",
            "liquidity:sofr_volume",
            "liquidity:bgcr_volume",
            "liquidity:tgcr_volume",
            "fed:iorb",
            "liquidity:nyfed_rrp",
            "liquidity:srf",
        ),
        chart_specs=(
            MacroChartSpec(
                "rrp_tga_stack",
                (
                    "liquidity:on_rrp",
                    "liquidity:tga",
                    "liquidity:fed_assets",
                    "liquidity:reserve_balances",
                    "liquidity:nyfed_rrp",
                    "liquidity:srf",
                    "liquidity:sofr_volume",
                    "liquidity:bgcr_volume",
                    "liquidity:tgcr_volume",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "rrp_tga_table",
                (
                    "liquidity:on_rrp",
                    "liquidity:tga",
                    "liquidity:fed_assets",
                    "liquidity:reserve_balances",
                    "liquidity:sofr",
                    "liquidity:bgcr",
                    "liquidity:tgcr",
                    "liquidity:sofr_volume",
                    "liquidity:bgcr_volume",
                    "liquidity:tgcr_volume",
                    "fed:iorb",
                    "liquidity:nyfed_rrp",
                    "liquidity:srf",
                ),
            ),
        ),
        related_routes=(
            "/macro/rates/fed-funds",
        ),
    ),
    "economy/gdp": MacroModuleConfig(
        module_id="economy/gdp",
        route_path="/macro/economy/gdp",
        title="GDP 增长",
        subtitle="实际 GDP、消费与增长代理",
        question="增长数据是否足够支撑风险资产盈利预期？",
        section="economy",
        required_concepts=("economy:gdp_real",),
        optional_concepts=(
            "economy:gdp_nominal",
            "economy:gdp_nowcast",
            "economy:industrial_production",
            "economy:housing_starts",
            "consumer:retail_sales",
            "consumer:pce_nominal",
            "consumer:pce_real",
            "consumer:saving_rate",
            "consumer:umich_sentiment",
            "labor:payrolls",
            "rates:dgs10",
        ),
        chart_specs=(
            MacroChartSpec(
                "real_gdp_history",
                (
                    "economy:gdp_real",
                    "economy:gdp_nominal",
                    "economy:industrial_production",
                    "consumer:pce_real",
                    "consumer:retail_sales",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "real_gdp_table",
                (
                    "economy:gdp_real",
                    "economy:gdp_nominal",
                    "economy:gdp_nowcast",
                    "economy:industrial_production",
                    "economy:housing_starts",
                    "consumer:pce_nominal",
                    "consumer:pce_real",
                    "consumer:retail_sales",
                    "consumer:saving_rate",
                    "consumer:umich_sentiment",
                    "labor:payrolls",
                ),
            ),
        ),
        related_routes=("/macro/economy/employment", "/macro/economy/inflation"),
    ),
    "economy/employment": MacroModuleConfig(
        module_id="economy/employment",
        route_path="/macro/economy/employment",
        title="就业市场",
        subtitle="失业率、非农、初请、职位空缺与工资",
        question="就业是在缓慢降温，还是触发增长风险？",
        section="economy",
        required_concepts=("labor:unemployment", "labor:payrolls", "labor:initial_claims"),
        optional_concepts=(
            "labor:job_openings",
            "labor:avg_hourly_earnings",
            "labor:participation",
            "fed:target_upper",
            "rates:dgs2",
        ),
        chart_specs=(
            MacroChartSpec(
                "employment_dashboard",
                (
                    "labor:unemployment",
                    "labor:payrolls",
                    "labor:initial_claims",
                    "labor:job_openings",
                    "labor:avg_hourly_earnings",
                    "labor:participation",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "employment_table",
                (
                    "labor:unemployment",
                    "labor:payrolls",
                    "labor:initial_claims",
                    "labor:job_openings",
                    "labor:avg_hourly_earnings",
                    "labor:participation",
                    "rates:dgs2",
                ),
            ),
        ),
        related_routes=("/macro/economy/gdp", "/macro/economy/inflation"),
    ),
    "economy/inflation": MacroModuleConfig(
        module_id="economy/inflation",
        route_path="/macro/economy/inflation",
        title="通胀数据",
        subtitle="CPI、PPI、PCE、GDP 平减指数与通胀预期",
        question="通胀压力是否足以改变政策预期？",
        section="economy",
        required_concepts=("inflation:cpi", "inflation:core_cpi", "inflation:ppi"),
        optional_concepts=(
            "inflation:gdp_deflator",
            "inflation:pce",
            "inflation:core_pce",
            "inflation:5y_breakeven",
            "inflation:10y_breakeven",
            "inflation:5y5y_forward",
            "inflation:mich_1y_expectation",
        ),
        chart_specs=(
            MacroChartSpec(
                "inflation_dashboard",
                (
                    "inflation:cpi",
                    "inflation:core_cpi",
                    "inflation:ppi",
                    "inflation:pce",
                    "inflation:core_pce",
                    "inflation:10y_breakeven",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "inflation_table",
                (
                    "inflation:cpi",
                    "inflation:core_cpi",
                    "inflation:ppi",
                    "inflation:gdp_deflator",
                    "inflation:pce",
                    "inflation:core_pce",
                    "inflation:5y_breakeven",
                    "inflation:10y_breakeven",
                    "inflation:5y5y_forward",
                    "inflation:mich_1y_expectation",
                ),
            ),
        ),
        related_routes=("/macro/economy/gdp", "/macro/rates/real-rates"),
    ),
    "volatility/vix": MacroModuleConfig(
        module_id="volatility/vix",
        route_path="/macro/volatility/vix",
        title="VIX 结构",
        subtitle="VIX、VIX1D、VIX9D、VIX3M、VVIX/SKEW、跨资产隐含波动率与期货代理",
        question="VIX 期限结构是在 carry，还是进入倒挂压力？",
        section="volatility",
        required_concepts=("vol:vix", "vol:vix3m"),
        optional_concepts=(
            "vol:vix1d",
            "vol:vix9d",
            "vol:vvix",
            "vol:skew",
            "vol:vxn",
            "vol:rvx",
            "vol:gvz",
            "vol:ovx",
            "vol:evz",
            "vol:move",
            "asset:vixy",
            "asset:vixm",
        ),
        chart_specs=(
            MacroChartSpec(
                "vix_term_proxy",
                (
                    "vol:vix",
                    "vol:vix1d",
                    "vol:vix9d",
                    "vol:vix3m",
                    "vol:move",
                    "vol:vxn",
                    "vol:rvx",
                    "vol:ovx",
                    "asset:vixy",
                    "asset:vixm",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "vix_term_proxy_table",
                (
                    "vol:vix",
                    "vol:vix1d",
                    "vol:vix9d",
                    "vol:vix3m",
                    "vol:vvix",
                    "vol:skew",
                    "vol:vxn",
                    "vol:rvx",
                    "vol:gvz",
                    "vol:ovx",
                    "vol:evz",
                    "vol:move",
                    "asset:vixy",
                    "asset:vixm",
                ),
            ),
        ),
        related_routes=("/macro/credit/stress", "/macro/assets/equities"),
    ),
    "credit/stress": MacroModuleConfig(
        module_id="credit/stress",
        route_path="/macro/credit/stress",
        title="信用压力分解",
        subtitle="OAS 分层、融资成本与风险资产确认",
        question="压力来自高收益尾部、投资级融资成本，还是 ETF 流动性？",
        section="credit",
        required_concepts=("credit:hy_oas", "credit:ig_oas", "credit:hy_ccc_oas"),
        optional_concepts=(
            "credit:aaa_oas",
            "credit:aa_oas",
            "credit:a_oas",
            "credit:bbb_oas",
            "credit:hy_bb_oas",
            "credit:hy_b_oas",
            "credit:hy_yield",
            "credit:ig_yield",
            "credit:stl_stress",
            "credit:nfci",
            "credit:anfci",
            "credit:sloos_ci_large_tightening",
            "credit:sloos_ci_small_tightening",
            "credit:sloos_ci_large_demand",
            "credit:sloos_ci_small_demand",
            "credit:business_delinquency",
            "credit:consumer_delinquency",
            "credit:business_charge_off",
            "credit:consumer_charge_off",
            "asset:hyg",
            "asset:lqd",
            "vol:vix",
        ),
        chart_specs=(
            MacroChartSpec(
                "credit_stress_stack",
                (
                    "credit:ig_oas",
                    "credit:bbb_oas",
                    "credit:hy_oas",
                    "credit:hy_bb_oas",
                    "credit:hy_b_oas",
                    "credit:hy_ccc_oas",
                    "vol:vix",
                ),
            ),
        ),
        table_specs=(
            MacroTableSpec(
                "credit_stress_table",
                (
                    "credit:ig_oas",
                    "credit:aaa_oas",
                    "credit:aa_oas",
                    "credit:a_oas",
                    "credit:bbb_oas",
                    "credit:hy_oas",
                    "credit:hy_bb_oas",
                    "credit:hy_b_oas",
                    "credit:hy_ccc_oas",
                    "credit:ig_yield",
                    "credit:hy_yield",
                    "credit:stl_stress",
                    "credit:nfci",
                    "credit:anfci",
                    "credit:sloos_ci_large_tightening",
                    "credit:sloos_ci_small_tightening",
                    "credit:sloos_ci_large_demand",
                    "credit:sloos_ci_small_demand",
                    "credit:business_delinquency",
                    "credit:consumer_delinquency",
                    "credit:business_charge_off",
                    "credit:consumer_charge_off",
                    "asset:hyg",
                    "asset:lqd",
                ),
            ),
        ),
        related_routes=("/macro/volatility/vix", "/macro/assets/bonds"),
    ),
}


def list_macro_module_configs() -> tuple[MacroModuleConfig, ...]:
    return tuple(_MODULE_CONFIGS[module_id] for module_id in MACRO_MODULE_IDS)


def get_macro_module_config(module_id: str) -> MacroModuleConfig:
    config = _MODULE_CONFIGS.get(module_id)
    if config is None:
        raise UnsupportedMacroModuleError(module_id)
    return config


__all__ = [
    "MACRO_MODULE_IDS",
    "MacroChartSpec",
    "MacroModuleConfig",
    "MacroTableSpec",
    "UnsupportedMacroModuleError",
    "get_macro_module_config",
    "list_macro_module_configs",
]
